// examples/taro-hooks-plugin-vue/src/pages/layout/useManualPullDownRefresh/index.vue
<template>
  <demo-content>
    <nut-button shape="square" type="primary" class="gap" block @click="start()"
      >开始下拉刷新</nut-button
    >
    <nut-button shape="square" type="primary" class="gap" block @click="stop()"
      >结束下拉刷新</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="start(2000)"
      >开始下拉刷新2S后停止</nut-button
    >
  </demo-content>
</template>

<script setup lang="ts">
import { useManualPullDownRefresh, useBackground } from 'taro-hooks';
import Mock from 'mockjs';

useBackground({ textStyle: 'dark', backgroundColor: Mock.Random.color() });

const [start, stop] = useManualPullDownRefresh();
</script>

// examples/taro-hooks-plugin/src/pages/layout/useManualPullDownRefresh/index.tsx
import React from 'react';
import { useManualPullDownRefresh, useBackground } from 'taro-hooks';
import Mock from 'mockjs';
import DemoContent from '@src/components/DemoContent';
import { Button } from '@taroify/core';

export default () => {
  const [start, stop] = useManualPullDownRefresh();
  useBackground({ textStyle: 'dark', backgroundColor: Mock.Random.color() });

  return (
    <DemoContent>
      <Button
        block
        color="primary"
        className="gap"
        onClick={() => start()}
        shape="square"
      >
        开始下拉刷新
      </Button>
      <Button
        block
        color="primary"
        className="gap"
        onClick={stop}
        shape="square"
      >
        结束下拉刷新
      </Button>
      <Button
        block
        color="primary"
        className="gap"
        onClick={() => start(2000)}
        shape="square"
      >
        开始下拉刷新2S后停止
      </Button>
    </DemoContent>
  );
};
