// examples/taro-hooks-plugin-vue/src/pages/environment/useEnv/index.vue
<template>
  <demo-content>
    <nut-radiogroup v-model="env">
      <nut-radio
        v-for="(value, key) in ENV_TYPE"
        :key="key"
        :disabled="value !== env"
        :label="value"
        shape="button"
        >环境值: {{ value }}</nut-radio
      >
    </nut-radiogroup>
  </demo-content>
</template>

<script setup lang="ts">
import { ENV_TYPE, showToast } from '@tarojs/taro';
import { useEffect } from '@taro-hooks/core';
import { useEnv } from 'taro-hooks';

const env = useEnv();

useEffect(() => {
  showToast({
    title: `当前环境: ${env}`,
    icon: 'none',
    mask: true,
  });
}, []);
</script>

// examples/taro-hooks-plugin/src/pages/environment/useEnv/index.tsx
import React from 'react';
import { ENV_TYPE, showToast } from '@tarojs/taro';
import { useEffect } from '@taro-hooks/core';

import DemoContent from '@src/components/DemoContent';
import { Radio, Cell } from '@taroify/core';

export default () => {
  const env = useEnv();

  useEffect(() => {
    showToast({
      title: `当前环境: ${env}`,
      icon: 'none',
      mask: true,
    });
  }, []);

  return (
    <DemoContent>
      <Radio.Group value={env}>
        <Cell.Group clickable>
          {Object.entries(ENV_TYPE).map(([key, value]) => (
            <Cell key={key} title={'环境值: ' + value}>
              <Radio disabled={value !== env} name={value} />
            </Cell>
          ))}
        </Cell.Group>
      </Radio.Group>
    </DemoContent>
  );
};
