// packages/app/src/pages/useMotion/index.tsx
import React, { useCallback } from 'react';
import { AtButton, AtList, AtListItem } from 'taro-ui';
import DocPage from '@components/DocPage';

import { useMotion, useModal } from 'taro-hooks';

export default () => {
  const [motionInfo, { stop, start, addListener, removeListener }] =
    useMotion(true);
  const [show] = useModal({
    title: 'useMotion listen',
    showCancel: false,
    confirmText: '监听成功',
  });

  const customListen = useCallback(
    (motion) => {
      removeListener(customListen);
      show({
        content: JSON.stringify(motion),
      });
    },
    [show, removeListener],
  );

  return (
    <DocPage title="useMotion 设备方向" panelTitle="useMotion">
      <AtButton onClick={() => addListener(customListen)}>
        增加一次监听并取消
      </AtButton>
      <AtButton className="gap" onClick={() => stop()}>
        停止所有
      </AtButton>
      <AtList>
        {Object.entries(motionInfo).map(([key, value]) => (
          <AtListItem title={key} key={key} note={value as string} />
        ))}
      </AtList>
    </DocPage>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/device/useMotion/index.vue
<template>
  <demo-content>
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleListen()"
      >增加一次监听并取消</nut-button
    >
    <nut-button shape="square" type="primary" class="gap" block @click="stop()"
      >停止所有</nut-button
    >

    <nut-cell-group title="方向信息">
      <nut-cell
        v-for="(value, key) in motion"
        :key="key"
        :title="key"
        :sub-title="$filters.stringify(value)"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useModal, useMotion } from 'taro-hooks';

const [motion, { start, stop, add, off }] = useMotion(true);

console.log(motion);

const show = useModal({
  title: 'useMotion',
  showCancel: false,
  mask: true,
});

const customListen = (result) => {
  show({
    content: JSON.stringify(result),
  });
  off(customListen);
};

const handleListen = async () => {
  try {
    await add(customListen);
  } catch (e) {
    show({ content: '监听失败' });
  }
};
</script>
