// examples/taro-hooks-plugin-vue/src/pages/wechat/useUserInfo/index.vue
<template>
  <demo-content>
    <nut-row type="flex" gutter="8" align="center" justify="center">
      <nut-col span="4"
        ><nut-avatar
          size="large"
          :icon="userInfo?.userInfo?.avatarUrl"
        ></nut-avatar
      ></nut-col>
      <nut-col span="20">
        <nut-row type="flex" flex-wrap="wrap" align="center" justify="center">
          <nut-col>昵称: {{ userInfo?.userInfo?.nickName }}</nut-col>
          <nut-col>性别: {{ userInfo?.userInfo?.gender }}</nut-col>
        </nut-row>
      </nut-col>
    </nut-row>
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="handleGetUserInfo()"
      >获取用户信息</nut-button
    >
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @tap="getUserProfile({ lang: 'zh_CN', desc: '仅作为小程序展示使用' })"
      >获取用户信息(包含敏感信息)</nut-button
    >
    <nut-cell-group title="用户信息">
      <nut-cell
        v-for="(value, key) in { ...(userInfo?.userInfo ?? {}), ...userInfo }"
        :key="key"
        :title="key"
        :sub-title="$filters.stringify(value)"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useUserInfo, useLogin, useModal } from 'taro-hooks';

const [userInfo = {}, { getUserInfo, getUserProfile }] = useUserInfo();
const { login } = useLogin();

const show = useModal({ mask: true, title: '获取结果', showCancel: false });

const handleGetUserInfo = async () => {
  let content = '获取成功';
  try {
    await login(true);
    await getUserInfo({ lang: 'zh_CN', withCredentials: true });
  } catch (e) {
    content = e.errMsg || e.message;
  }
  show({ content });
};
</script>

// packages/app/src/pages/useUserInfo/index.tsx
import React, { useCallback } from 'react';
import { AtRadio, AtAvatar, AtButton, AtNoticebar } from 'taro-ui';
import DocPage from '@components/DocPage';

import { useUserInfo, useLogin } from 'taro-hooks';
import { UserInfo } from '@tarojs/taro';
import { View, Text } from '@tarojs/components';

import 'taro-ui/dist/style/components/flex.scss';
import './index.less';

const MOCK = '1';

const transferOptions = (userInfo: UserInfo) =>
  Object.entries(userInfo).map(([key, value]) => ({
    label: key + ':',
    value: key,
    desc: JSON.stringify(value),
  }));

export default () => {
  const [userInfo, { getUserInfo, getUserProfile }] = useUserInfo();
  const [login] = useLogin();

  const handleGetUserInfo = useCallback(() => {
    login(true).then(() => {
      getUserInfo({ lang: 'zh_CN', withCredentials: true });
    });
  }, [login, getUserInfo]);

  return (
    <>
      <AtNoticebar marquee>该hook仅在小程序中使用</AtNoticebar>
      <DocPage title="useUserInfo 用户信息" panelTitle="useUserInfo">
        <View className="at-row at-row__align--center  at-row__justify--between userinfo">
          <View className="at-col-1 at-col--auto">
            <AtAvatar size="large" image={userInfo.avatarUrl} />
          </View>
          <View className="at-col-9 at-row at-row--wrap">
            <Text className="at-col-12 ellipsis">
              昵称: {userInfo.nickName}
            </Text>
            <Text className="at-col-12">
              性别:{' '}
              {!userInfo.gender
                ? '未知'
                : userInfo.gender === 1
                ? '男性'
                : '女性'}
            </Text>
          </View>
        </View>
        <AtButton onClick={handleGetUserInfo}>获取用户信息</AtButton>
        <AtButton
          className="gap"
          onClick={() =>
            getUserProfile({ lang: 'zh_CN', desc: '仅作为小程序展示使用' })
          }
        >
          获取用户信息(包含敏感)
        </AtButton>
        <AtRadio
          options={transferOptions(userInfo)}
          value={MOCK}
          onClick={console.log}
        />
      </DocPage>
    </>
  );
};
