// examples/taro-hooks-plugin-vue/src/pages/feedback/useAlertBeforeUnload/index.vue
<template>
  <demo-content>
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="disable()"
      >取消离开页面弹窗</nut-button
    >
  </demo-content>
</template>

<script setup lang="ts">
import { useAlertBeforeUnload } from 'taro-hooks';

import { useDidShow } from '@tarojs/taro';

const { enable, disable } = useAlertBeforeUnload();

useDidShow(() => {
  enable('您要离开此页面吗?');
});
</script>

// examples/taro-hooks-plugin/src/pages/feedback/useAlertBeforeUnload/index.tsx
import React from 'react';
import { useAlertBeforeUnload } from 'taro-hooks';

import { useDidShow } from '@tarojs/taro';
import DemoContent from '@src/components/DemoContent';
import { Button } from '@taroify/core';

export default () => {
  const { enable, disable } = useAlertBeforeUnload();

  useDidShow(() => {
    enable('您要离开此页面吗?');
  });

  return (
    <DemoContent>
      <Button
        block
        color="primary"
        className="gap"
        onClick={() => disable()}
        shape="square"
      >
        取消离开页面弹窗
      </Button>
    </DemoContent>
  );
};
