// ant-mobile-taro/src/components/desense-text/desense-text.tsx
import React, { FC } from 'react'
import classnames from 'classnames'
import { View } from '@tarojs/components'
import { NativeProps, withNativeProps } from '../../utils/native-props'
import { mergeProps } from '../../utils/with-default-props'
import { EyeClose, Eye } from 'ant-mobile-icon-taro/es/index.react'
import { usePropsValue } from '../../utils/use-props-value'

const classPrefix = 'adm-desense-text'

export type DesenseTextProps = {
  desense?: boolean
  defaultDesense?: boolean
  text?: React.ReactNode
  desenseText?: React.ReactNode
  onChange?: (v: boolean) => void
} & NativeProps

const defaultProps = {
  defaultDesense: true,
}

export const DesenseText: FC<DesenseTextProps> = p => {
  const props = mergeProps(defaultProps, p)
  const { text, desenseText } = props

  const [isDesense, setIsDesense] = usePropsValue<boolean>({
    value: props.desense,
    defaultValue: props.defaultDesense,
    onChange: props.onChange,
  })
  return withNativeProps(
    props,
    <View className={classPrefix}>
      {isDesense ? desenseText : text}
      <View
        className={classnames(`${classPrefix}-icon-wrap`, 'adm-plain-anchor')}
        onClick={() => {
          setIsDesense(!isDesense)
        }}
      >
        {isDesense ? <EyeClose /> : <Eye />}
      </View>
    </View>
  )
}

// ant-mobile-taro/src/components/desense-text/desense-text.vue.tsx
/* eslint-disable react/react-in-jsx-scope */
import { computed, toRefs, ref } from 'vue'
import classnames from 'classnames'
import { View } from '@tarojs/components'
import { withNativeProps } from '../../utils/native-props.vue'
import { EyeClose, Eye } from 'ant-mobile-icon-taro/es/index.vue'

const classPrefix = 'adm-desense-text'

export const DesenseTextProps = {
  desense: Boolean,
  defaultDesense: {
    type: Boolean,
    default: true,
  },
  text: [Function, String, Object],
  desenseText: [Function, String, Object],
}

export const DesenseText = withNativeProps({
  name: 'DesenseText',
  props: DesenseTextProps,
  emits: ['change'],
  setup(props, { attrs, slots, emit }) {
    const { desense, defaultDesense } = toRefs(props)
    const controlDesense = ref()

    const isDesense = computed(() => {
      return typeof controlDesense.value !== 'undefined'
        ? controlDesense.value
        : desense.value || defaultDesense.value
    })

    return () => (
      <View className={classnames(classPrefix, attrs.className, attrs.class)}>
        {isDesense.value
          ? slots.desenseText?.() || props.desenseText
          : slots.text?.() || props.text}
        <View
          className={classnames(`${classPrefix}-icon-wrap`, 'adm-plain-anchor')}
          onClick={() => {
            controlDesense.value = !isDesense.value
            emit('change', !isDesense.value)
          }}
        >
          {isDesense.value ? <EyeClose /> : <Eye />}
        </View>
      </View>
    )
  },
})
