// packages/app/src/pages/useStorage/index.tsx
import React, { useCallback, useEffect } from 'react';
import { AtList, AtListItem, AtMessage, AtDivider, AtCard } from 'taro-ui';
import { View } from '@tarojs/components';
import DocPage from '@components/DocPage';

import { useStorage } from 'taro-hooks';
import Taro from '@tarojs/taro';
import Mock from 'mockjs';

import 'taro-ui/dist/style/components/icon.scss';
import 'taro-ui/dist/style/components/flex.scss';

export default () => {
  const [storageInfo, { set, get, remove }] = useStorage();

  useEffect(() => {
    // remove for web detail error
    remove();
  }, [remove]);

  const handleSetStorage = useCallback(() => {
    set(Mock.mock('@name()'), Mock.mock('@name()')).then((res: boolean) => {
      Taro.atMessage({
        message: '设置缓存' + res ? '成功' : '失败',
      });
    });
  }, [set]);

  const handleGetStorage = useCallback(async () => {
    const { keys } = storageInfo;
    let message = '获取缓存';
    if (!keys.length) {
      message = '暂无缓存可获取';
    } else {
      const randomIndex = Math.ceil(Math.random() * keys.length);
      const data = await get(keys[randomIndex]);
      if (data) {
        message += `: ${data}`;
      } else {
        message += '失败';
      }
    }
    Taro.atMessage({
      message,
    });
  }, [storageInfo, get]);

  const handleRemoveStorage = useCallback(
    async (all?: boolean) => {
      const { keys } = storageInfo;
      if (keys.length && !all) {
        const result = await remove(keys[0]);
        Taro.atMessage({
          message: '移除单个缓存' + result ? '成功' : '失败',
        });
      } else {
        const result = await remove();
        Taro.atMessage({
          message: '移除缓存' + result ? '成功' : '失败',
        });
      }
    },
    [storageInfo, remove],
  );

  return (
    <>
      <AtMessage />
      <DocPage title="useStorage 数据缓存" panelTitle="useStorage">
        <AtList>
          <AtListItem title="set" note="设置缓存" onClick={handleSetStorage} />
          <AtListItem title="get" note="获取缓存" onClick={handleGetStorage} />
          <AtListItem
            title="remove"
            note="移除一个缓存"
            onClick={() => handleRemoveStorage()}
          />
          <AtListItem
            title="remove"
            note="移除所有缓存"
            onClick={() => handleRemoveStorage(true)}
          />
        </AtList>
        <AtDivider content="下面为缓存展示" />
        <AtCard title="当前缓存个数">
          <View>缓存占用: {storageInfo.currentSize}</View>
          <View>缓存限制: {storageInfo.limitSize}</View>
          <View>当前缓存数量: {storageInfo.keys.length}</View>
          <View>分别为: </View>
          {Object.entries(storageInfo.storage).map(([key, value]) => (
            <View key={key}>
              {key} - {JSON.stringify(value)}
            </View>
          ))}
        </AtCard>
      </DocPage>
    </>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/basic/useStorage/index.vue
<template>
  <demo-content>
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="handleAdd()"
      >随机设置缓存!</nut-button
    >
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="handleGet()"
      >随机获取缓存!</nut-button
    >
    <nut-button
      class="gap"
      shape="square"
      type="danger"
      block
      @click="handleRemove()"
      >随机移除缓存!</nut-button
    >
    <nut-cell-group title="当前缓存个数">
      <nut-cell
        title="缓存占用"
        :sub-title="String(storageInfo.currentSize)"
      ></nut-cell>
      <nut-cell
        title="缓存限制"
        :sub-title="String(storageInfo.limitSize)"
      ></nut-cell>
      <nut-cell
        title="当前缓存数量"
        :sub-title="String(storageInfo.keys?.length)"
      ></nut-cell>
      <nut-cell title="分别为:"></nut-cell>
      <nut-cell
        v-for="(value, key) in storageInfo.storage"
        :key="key"
        :title="key"
        :sub-title="$filters.stringify(value)"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useStorage, useToast } from 'taro-hooks';
import { escapeState } from '@taro-hooks/shared';
import Mock from 'mockjs';

const [storageInfo, { set, get, remove }] = useStorage();
const { show } = useToast({ mask: true, title: '操作成功' });

const handleAdd = () => {
  set<string>(Mock.Random.word(), Mock.Random.name()).then(() => {
    show();
  });
};

const generateKey = () => {
  const randomIndex = Math.max(
    Math.ceil(Math.random() * escapeState(storageInfo).keys.length),
    escapeState(storageInfo).keys.length - 1,
  );
  return escapeState(storageInfo).keys[randomIndex];
};

const handleGet = () => {
  get<string>(generateKey()).then((res) => {
    show({ title: res ?? '获取失败' });
  });
};

const handleRemove = () => {
  remove(generateKey()).then(() => show());
};
</script>
