// examples/taro-hooks-plugin-vue/src/pages/basic/useDeviceInfo/index.vue
<template>
  <demo-content>
    <nut-cell
      v-for="(value, key) in deviceInfo"
      :key="key"
      :title="key"
      :sub-title="$filters.stringify(value)"
    ></nut-cell>
  </demo-content>
</template>

<script setup lang="ts">
import { useDeviceInfo } from 'taro-hooks';

const deviceInfo = useDeviceInfo();
</script>

// examples/taro-hooks-plugin/src/pages/basic/useDeviceInfo/index.tsx
import React from 'react';
import DemoContent from '@src/components/DemoContent';
import { Cell } from '@taroify/core';
import { useDeviceInfo } from 'taro-hooks';

export default () => {
  const deviceInfo = useDeviceInfo();

  return (
    <DemoContent>
      <Cell.Group clickable>
        {Object.entries(deviceInfo).map(([key, value]) => (
          <Cell key={key} title={key} brief={JSON.stringify(value)}></Cell>
        ))}
      </Cell.Group>
    </DemoContent>
  );
};
