// packages/app/src/components/DemoBlock/index.tsx
import React, { FC } from 'react';
import { View } from '@tarojs/components';
import './index.less';

interface Props {
  title: string;
  padding?: string;
  border?: string;
  background?: string;
}

const DemoBlock: FC<Props> = (props) => {
  return (
    <View className="demo-lock">
      <View className="title">{props.title}</View>
      <View
        className="content"
        style={{
          padding: props.padding,
          background: props.background,
          border: props.border,
        }}
      >
        {props.children}
      </View>
    </View>
  );
};

DemoBlock.defaultProps = {
  padding: '12px 12px',
  background: '#ffffff',
};

export default DemoBlock;

// packages/app-vue/src/components/DemoBlock/index.vue
<template>
  <view class="demo-lock">
    <view class="title">{{ title }}</view>
    <view class="content" :style="style"><slot /></view>
  </view>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import './index.less';

export default defineComponent({
  props: {
    title: {
      type: String,
      required: true,
    },
    padding: {
      type: String,
      default: '12px 12px',
    },
    background: {
      type: String,
      default: '#ffffff',
    },
    border: String,
  },
  setup(props) {
    const { padding, background, border } = props;
    return {
      style: `padding: ${padding}; background: ${background}; ${
        border ? 'border: ' + border : ''
      }`,
      title: props.title,
    };
  },
});
</script>
