// examples/taro-hooks-plugin/src/components/DemoContent/index.tsx
import React, { PropsWithChildren } from 'react';
import { View } from '@tarojs/components';
import { useRouter } from '@tarojs/taro';
import './index.scss';

interface IDemoContentProps {
  title?: string;
  desc?: string;
}

function DemoContent({
  title,
  desc,
  children,
}: PropsWithChildren<IDemoContentProps>) {
  const { params = {} } = useRouter();

  const { title: urlTitle } = transferParams(params);

  return (
    <View className="demo-content">
      <View className="demo-content-title">{urlTitle ?? title}</View>
      <View className="demo-content-desc">{desc}</View>
      <View className="demo-content-wrapper">{children}</View>
    </View>
  );
}

export default DemoContent;

function transferParams(params) {
  // @ts-ignore
  return Object.fromEntries(
    Object.entries(params).map(([key, value]) => [
      key,
      decodeURIComponent(value as string),
    ]),
  );
}

// examples/taro-hooks-plugin-vue/src/components/DemoContent/index.vue
<template>
  <view class="demo-content">
    <view class="demo-content-title">{{ title || params.title }}</view>
    <view class="demo-content-desc">{{ desc }}</view>
    <view class="demo-content-wrapper">
      <slot />
    </view>
  </view>
</template>

<script>
import { useTaroRef, useRouter } from '@tarojs/taro';
export default {
  name: 'DemoContent',
  props: {
    title: String,
    desc: String,
  },
  setup() {
    const demoRef = useTaroRef();
    const { params = {} } = useRouter();

    function transferParams(params) {
      return Object.fromEntries(
        Object.entries(params).map(([key, value]) => [
          key,
          decodeURIComponent(value),
        ]),
      );
    }

    return {
      params: transferParams(params),
    };
  },
};
</script>

<style>
.demo-content {
  padding: 8px;
  background: white;
}

.demo-content-title {
  margin: 15px auto 5px;
  font-size: 14px;
  color: #909ca4;
  font-weight: 600;
}

.demo-content-desc {
  margin: 0 auto 5px;
  font-size: 12px;
  color: #909ca4;
  font-weight: 400;
}

.demo-content-title:first-child {
  margin-top: 0;
}

.demo-content-wrapper {
  font-size: 14px;
  font-weight: 400;
}
</style>
