// ant-mobile-taro/src/components/steps/steps.vue.tsx
/* eslint-disable react/react-in-jsx-scope */
import { toRefs, h, PropType } from 'vue'
import { View, Text } from '@tarojs/components'
import classNames from 'classnames'
import { withNativeProps } from '../../utils/native-props.vue'

const classPrefix = `adm-steps`
const stepClassPrefix = `adm-step`

const defaultIcon = <Text className={`${stepClassPrefix}-icon-dot`} />

type Direction = 'horizontal' | 'vertical'

export const StepsProps = {
  current: {
    type: Number,
    default: 0,
  },
  direction: {
    type: String as PropType<Direction>,
    default: 'horizontal',
  },
}

export const Steps = withNativeProps({
  name: 'Steps',
  props: StepsProps,
  setup(props, { attrs, slots }) {
    const { direction, current } = toRefs(props)
    const classString = classNames(
      classPrefix,
      `${classPrefix}-${direction.value}`,
      attrs.className,
      attrs.class
    )
    return () => (
      <View className={classString}>
        {slots.default &&
          slots.default().map((child, index) => {
            const childProps = child.props
            let status = childProps?.status || 'wait'

            if (index < current.value) {
              status = childProps?.status || 'finish'
            } else if (index === current.value) {
              status = childProps?.status || 'process'
            }

            // @ts-ignore
            const icon =
              childProps?.icon ?? child?.children?.icon ?? defaultIcon
            return h(child, {
              status,
              icon,
            })
          })}
      </View>
    )
  },
})

// ant-mobile-taro/src/components/steps/steps.tsx
import React, { FC } from 'react'
import { View, Text } from '@tarojs/components'
import classNames from 'classnames'
import { StepProps } from './step'
import { mergeProps } from '../../utils/with-default-props'
import { NativeProps, withNativeProps } from '../../utils/native-props'

const classPrefix = `adm-steps`
const stepClassPrefix = `adm-step`

const defaultIcon = <Text className={`${stepClassPrefix}-icon-dot`} />

type Direction = 'horizontal' | 'vertical'

export type StepsProps = {
  current?: number
  direction?: Direction
} & NativeProps

const defaultProps = {
  current: 0,
  direction: 'horizontal',
}

export const Steps: FC<StepsProps> = p => {
  const props = mergeProps(defaultProps, p)
  const { direction, current } = props
  const classString = classNames(classPrefix, `${classPrefix}-${direction}`)

  return withNativeProps(
    props,
    <View className={classString}>
      {React.Children.map(props.children, (child, index) => {
        if (!React.isValidElement(child)) {
          return child
        }
        const props = child.props as StepProps
        let status = props.status || 'wait'

        if (index < current) {
          status = props.status || 'finish'
        } else if (index === current) {
          status = props.status || 'process'
        }

        const icon = props.icon ?? defaultIcon

        return React.cloneElement(child, {
          status,
          icon,
        })
      })}
    </View>
  )
}
