// examples/taro-hooks-plugin-vue/src/pages/basic/usePage/index.vue
<template>
  <demo-content>
    <nut-cell title="路由栈长度" :sub-title="stackLength"></nut-cell>
    <nut-cell
      title="当前页面信息"
      :sub-title="$filters.stringify(pageInstance)"
    ></nut-cell>
  </demo-content>
</template>

<script setup lang="ts">
import { usePage } from 'taro-hooks';

const [stackLength, { pageInstance = {} }] = usePage();
</script>

// examples/taro-hooks-plugin/src/pages/basic/usePage/index.tsx
import React from 'react';
import DemoContent from '@src/components/DemoContent';
import { Cell } from '@taroify/core';
import { usePage } from 'taro-hooks';

export default () => {
  const [stackLength, { pageInstance = {} }] = usePage();

  return (
    <DemoContent>
      <Cell.Group clickable>
        <Cell title="路由栈长度" brief={stackLength}></Cell>
        <Cell title="当前页面信息" brief={JSON.stringify(pageInstance)}></Cell>
      </Cell.Group>
    </DemoContent>
  );
};
