// examples/taro-hooks-plugin-vue/src/pages/feedback/useActionSheet/index.vue
<template>
  <demo-content>
    <nut-button shape="square" type="primary" class="gap" block @click="show()"
      >展示带初始配置的ActionSheet</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleChangeOption()"
      >展示新配置的ActionSheet</nut-button
    >
  </demo-content>
</template>

<script setup lang="ts">
import { useActionSheet, useToast } from 'taro-hooks';
import { escapeState } from '@taro-hooks/shared';
import { useTaroEffect } from '@tarojs/taro';

const { show, tapItem } = useActionSheet({ itemList: ['A', 'B', 'C'] });
const { show: showToast } = useToast({ duration: 2000, mask: true });

useTaroEffect(() => {
  if (escapeState(tapItem)) {
    const { tapIndex, tapItem: item } = escapeState(tapItem);
    showToast({ title: `${tapIndex}/${item}` });
  }
}, [tapItem]);

const handleChangeOption = () => {
  show({
    itemColor: '#C5D9E8',
    itemList: ['taro', 'hooks', 'taro-hooks'],
  });
};
</script>

// packages/app/src/pages/useActionSheet/index.tsx
import React, { useCallback } from 'react';
import { AtButton } from 'taro-ui';
import DocPage from '@components/DocPage';

import { useActionSheet, useToast } from 'taro-hooks';
import { showActionSheet } from '@tarojs/taro';

export default () => {
  const [showToast] = useToast({ mask: true });

  const onActionItemTap = useCallback(
    (tapIndex, tapItem) => {
      showToast({
        title: tapIndex + ': ' + tapItem,
      });
    },
    [showToast],
  );

  const [show] = useActionSheet({
    itemList: ['A', 'B', 'C'],
    onActionItemTap,
  });

  const showCustomActionSheet = useCallback(() => {
    show({
      itemColor: '#C5D9E8',
      itemList: ['taro', 'hooks', 'taro-hooks'],
    }).then((res: showActionSheet.SuccessCallbackResult) => {
      showToast({
        title: String(res.tapIndex),
      });
    });
  }, [show, showToast]);

  return (
    <>
      <DocPage title="useActionSheet 操作菜单" panelTitle="useActionSheet">
        <AtButton onClick={show}>展示带初始配置ActionSheet</AtButton>
        <AtButton className="gap" onClick={showCustomActionSheet}>
          展示新配置ActionSheet
        </AtButton>
      </DocPage>
    </>
  );
};
