// packages/app/src/pages/useRequest/debounce/index.tsx
/**
 * desc: 通过设置 `options.debounceInterval` ，则进入防抖模式。此时如果频繁触发 `run` ，则会以防抖策略进行请求。
 */
import React, { useEffect, useState } from 'react';
import { useRequest } from 'taro-hooks';
import Mock from 'mockjs';

import { AtInput, AtList, AtListItem } from 'taro-ui';
import { View } from '@tarojs/components';
import DocPage from '@components/DocPage';

async function getEmail(search: string): Promise<string[]> {
  console.log(search);
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock({ 'data|5': ['@email()'] }).data);
    }, 300);
  });
}

const DebounceRequest = () => {
  const { data, loading, run } = useRequest(getEmail, {
    debounceInterval: 500,
    manual: true,
  });

  const [value, setValue] = useState<string>();

  useEffect(() => {
    value && run(value);
  }, [value, run]);

  return (
    <DocPage title="useRequest 请求" panelTitle="防抖">
      <View>Enter quickly to see the effect</View>
      <AtInput
        name="email"
        value={value}
        onChange={(e) => setValue(e as string)}
        placeholder="Select Emails"
      />
      {loading ? (
        <View>loading...</View>
      ) : (
        <AtList>
          {data && data.map((i: string) => <AtListItem key={i} title={i} />)}
        </AtList>
      )}
    </DocPage>
  );
};

export default DebounceRequest;

// examples/taro-hooks-plugin-vue/src/pages/network/useRequest/debounce/index.vue
<template>
  <block>
    <demo-content title="防抖">
      <nut-row>
        <nut-input
          placeholder="Search Emails"
          @update:model-value="request.run($event)"
        />
      </nut-row>
      <view v-if="request.loading">Loading...</view>
      <template v-else>
        <view v-for="item in request.data" :key="item">{{ item }}</view>
      </template>
    </demo-content>
  </block>
</template>

<script>
import { useRequest } from 'taro-hooks';

import Mock from 'mockjs';

async function getEmail(search) {
  console.log('debounce getEmail', search);
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock({ 'data|5': ['@email()'] }).data);
    }, 300);
  });
}

export default {
  setup() {
    const request = useRequest(getEmail, {
      debounceWait: 1000,
      manual: true,
    });

    return { request };
  },
};
</script>
