// packages/app/src/pages/useVibrate/index.tsx
import React from 'react';
import { AtButton } from 'taro-ui';
import DocPage from '@components/DocPage';

import { useVibrate } from 'taro-hooks';

export default () => {
  const [vibrateAction] = useVibrate();
  const [vibrateIntervalAction, stopVibrateAction] = useVibrate(true);

  return (
    <DocPage title="useVibrate 震动反馈" panelTitle="useVibrate">
      <AtButton onClick={() => vibrateAction()}>短震动触感按钮</AtButton>
      <AtButton className="gap" onClick={() => vibrateAction(true)}>
        长震动触感按钮
      </AtButton>
      <AtButton onClick={() => vibrateIntervalAction()}>
        持续短震动触感按钮
      </AtButton>
      <AtButton
        className="gap"
        onClick={() => {
          stopVibrateAction();
          vibrateIntervalAction(true);
        }}
      >
        持续长震动触感按钮
      </AtButton>
      <AtButton onClick={() => stopVibrateAction()}>关闭持续震动</AtButton>
    </DocPage>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/device/useVibrate/index.vue
<template>
  <demo-content>
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="vibrate()"
      >短震动触感按钮</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="vibrate(true)"
      >长震动触感按钮</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="vibrateInterval()"
      >持续短震动触感按钮</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="vibrateInterval(true)"
      >持续长震动触感按钮</nut-button
    >
    <nut-button shape="square" type="primary" class="gap" block @click="clear()"
      >关闭持续震动</nut-button
    >
  </demo-content>
</template>

<script setup lang="ts">
import { useVibrate } from 'taro-hooks';

const { vibrate } = useVibrate();
const { vibrate: vibrateInterval, clear } = useVibrate(true);
</script>
