// ant-mobile-taro/src/components/safe-area/safe-area.tsx
import { FC } from 'react'
import { View } from '@tarojs/components'
import { NativeProps, withNativeProps } from '../../utils/native-props'
import React from 'react'
import classNames from 'classnames'

const classPrefix = 'adm-safe-area'

export type SafeAreaProps = {
  position: 'top' | 'bottom'
} & NativeProps

export const SafeArea: FC<SafeAreaProps> = props => {
  return withNativeProps(
    props,
    <View
      className={classNames(
        classPrefix,
        `${classPrefix}-position-${props.position}`
      )}
    />
  )
}

// ant-mobile-taro/src/components/safe-area/safe-area.vue.tsx
/* eslint-disable react/react-in-jsx-scope */
import { PropType } from 'vue'
import { View } from '@tarojs/components'
import { withNativeProps } from '../../utils/native-props.vue'
import classNames from 'classnames'

const classPrefix = 'adm-safe-area'

export type SafeAreaPosition = 'top' | 'bottom'

export const SafeAreaProps = {
  position: String as PropType<SafeAreaPosition>,
}

export const SafeArea = withNativeProps({
  name: 'SafeArea',
  props: SafeAreaProps,
  setup(props) {
    return () => (
      <View
        className={classNames(
          classPrefix,
          `${classPrefix}-position-${props.position}`
        )}
      />
    )
  },
})
