// examples/taro-hooks-plugin/src/pages/network/useRequest/refreshDeps/index.tsx
import React from 'react';
import DemoContent from '@src/components/DemoContent';
import { Field, ActionSheet } from '@taroify/core';

import { useTaroState } from '@tarojs/taro';
import { useRequest } from 'taro-hooks';

const userSchool = (id: string) => {
  switch (id) {
    case '1':
      return 'Tsinghua University';
    case '2':
      return 'Beijing University';
    case '3':
      return 'Zhejiang University';
    default:
      return '';
  }
};

async function getUserSchool(userId: string): Promise<string> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(userSchool(userId));
    }, 1000);
  });
}

export default () => {
  const [userId, setUserId] = useTaroState('1');
  const [open, setOpen] = useTaroState(false);
  const { data, loading } = useRequest(() => getUserSchool(userId), {
    refreshDeps: [userId],
  });

  return (
    <DemoContent title="依赖刷新">
      <Field align="center" onClick={() => setOpen(true)}>
        {userId} (click here)
      </Field>
      <Field align="start">School: {loading ? 'Loading' : data}</Field>
      <ActionSheet
        open={open}
        onSelect={(event) => {
          setUserId(event.value);
          setOpen(false);
        }}
        onClose={setOpen}
      >
        <ActionSheet.Action value="1" name="user 1" />
        <ActionSheet.Action value="2" name="user 2" />
        <ActionSheet.Action value="3" name="user 3" />
      </ActionSheet>
    </DemoContent>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/network/useRequest/refreshDeps/index.vue
<template>
  <demo-content title="依赖刷新">
    <view>School: {{ request.loading ? 'Loading...' : request.data }}</view>
    <nut-row justify="center">
      <nut-button
        :loading="request.loading"
        size="small"
        type="primary"
        shape="square"
        block
        @click="setOpen(true)"
      >
        userId: {{ userId }}(click me!)
      </nut-button>
    </nut-row>
    <nut-actionsheet
      v-model:visible="open"
      :menu-items="menuItems"
      @choose="handleChoose($event)"
    ></nut-actionsheet>
  </demo-content>
</template>

<script>
import { useRequest } from 'taro-hooks';
import { useTaroState } from '@tarojs/taro';
import { escapeState } from '@taro-hooks/shared';

const userSchool = (id) => {
  switch (id) {
    case '1':
      return 'Tsinghua University';
    case '2':
      return 'Beijing University';
    case '3':
      return 'Zhejiang University';
    default:
      return '';
  }
};

async function getUserSchool(userId) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(userSchool(userId));
    }, 1000);
  });
}

export default {
  setup() {
    const menuItems = [
      { value: '1', name: 'user 1' },
      { value: '2', name: 'user 2' },
      { value: '3', name: 'user 3' },
    ];
    const [userId, setUserId] = useTaroState('1');
    const [open, setOpen] = useTaroState(false);
    const request = useRequest(() => getUserSchool(escapeState(userId)), {
      refreshDeps: [userId],
    });

    const handleChoose = (item) => {
      setUserId(item.value);
      setOpen(false);
    };

    return { request, userId, open, handleChoose, menuItems, setOpen };
  },
};
</script>
