// packages/app/src/pages/useModal/index.tsx
import React, { useCallback } from 'react';
import { AtButton } from 'taro-ui';
import DocPage from '@components/DocPage';

import { useModal } from 'taro-hooks';

export default () => {
  const [show] = useModal({
    title: 'initial title',
    content: 'initial content',
  });

  const showCustomModal = useCallback(() => {
    show({
      title: 'taro hooks',
      content: 'taro hooks 还不戳！',
      showCancel: false,
      confirmText: '确实！',
      confirmColor: '#4569d4',
    });
  }, [show]);

  return (
    <>
      <DocPage title="useModal 模态对话框" panelTitle="useModal">
        <AtButton onClick={show}>展示带初始配置Modal</AtButton>
        <AtButton className="gap" onClick={showCustomModal}>
          展示新配置Modal
        </AtButton>
      </DocPage>
    </>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/feedback/useModal/index.vue
<template>
  <demo-content>
    <nut-button shape="square" type="primary" class="gap" block @click="show()"
      >展示带初始配置的Modal</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleChangeOption()"
      >展示新配置的Modal</nut-button
    >
  </demo-content>
</template>

<script setup lang="ts">
import { useModal } from 'taro-hooks';

const show = useModal({ title: 'initial title', content: 'initial content' });

const handleChangeOption = () => {
  show({
    title: 'taro-hooks-next',
    content: '你相信光么!',
    showCancel: false,
    confirmText: '当然!',
  });
};
</script>
