// packages/app/src/components/DemoDescription/index.tsx
import React, { FC, ReactNode } from 'react';
import { View } from '@tarojs/components';
import './index.less';

const DemoDescription: FC<{
  content?: ReactNode;
}> = (props) => {
  return (
    <View className="demo-description">{props.content || props.children}</View>
  );
};

export default DemoDescription;

// packages/app-vue/src/components/DemoDescription/index.vue
<template>
  <view class="demo-description">
    <template v-if="content">{{ content }}</template>
    <template v-else><slot /></template>
  </view>
</template>

<script lang="ts">
import { defineComponent, VueElement } from 'vue';
import './index.less';

export default defineComponent({
  props: {
    content: VueElement,
  },
  setup(props) {
    return {
      content: props.content,
    };
  },
});
</script>
