// packages/app/src/pages/useVideo/index.tsx
import React, { useCallback, useState } from 'react';
import { AtNoticebar, AtButton } from 'taro-ui';
import { Video } from '@tarojs/components';

import DocPage from '@components/DocPage';

import { useVideo, useEnv, useToast } from 'taro-hooks';
import { chooseVideo, ENV_TYPE, useReady } from '@tarojs/taro';

export default () => {
  const env = useEnv();
  const [show] = useToast({ mask: true });
  const [videoContext, { choose, save, create }] = useVideo({
    camera: 'back',
    sourceType: ['camera', 'album'],
  });
  const [videoResult, setVideoResult] =
    useState<chooseVideo.SuccessCallbackResult>();

  useReady(() => {
    if (env && env !== ENV_TYPE.WEB) {
      create('useVideoContext');
    }
  });

  const handleChooseVideo = useCallback(() => {
    choose({ maxDuration: 10 }).then(setVideoResult);
  }, [choose]);

  const handleSaveVideo = useCallback(
    (filePath) => {
      save(filePath)
        .then(() => {
          show({
            title: '保存成功',
          });
        })
        .catch(() => {
          show({
            icon: 'none',
            title: '保存失败',
          });
        });
    },
    [save, show],
  );

  return (
    <>
      <AtNoticebar marquee>当前hook不支持h5, 请移步小程序体验</AtNoticebar>
      <DocPage title="useVideo 视频" panelTitle="useVideo">
        <Video
          id="useVideoContext"
          className="demo"
          src={videoResult?.tempFilePath || ''}
        />
        <AtButton
          disabled={env === ENV_TYPE.WEB}
          className="gap"
          onClick={handleChooseVideo}
        >
          选择视频
        </AtButton>
        <AtButton
          disabled={!videoContext || !videoResult?.tempFilePath}
          onClick={() => videoContext.play()}
        >
          播放视频
        </AtButton>
        <AtButton
          className="gap"
          disabled={!videoContext || !videoResult?.tempFilePath}
          onClick={() => videoContext.pause()}
        >
          暂停视频
        </AtButton>
        <AtButton
          disabled={env === ENV_TYPE.WEB || !videoResult?.tempFilePath}
          onClick={() => handleSaveVideo(videoResult?.tempFilePath)}
        >
          保存视频
        </AtButton>
      </DocPage>
    </>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/media/useVideo/index.vue
<template>
  <demo-content>
    <video :id="videoId" :src="videoInfo?.tempFilePath"></video>
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleChoose()"
      >选择视频</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleVideoAction('play')"
      >播放视频</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleVideoAction('pause')"
      >暂停视频</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleCompress()"
      >压缩视频(小程序独有)</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="open(videoInfo?.tempFilePath)"
      >打开视频编辑器(小程序独有)</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="save(videoInfo?.tempFilePath)"
      >保存视频</nut-button
    >
    <nut-cell-group title="视频信息">
      <nut-cell
        v-for="(value, key) in videoSummary ?? {}"
        :key="key"
        :title="key"
        :sub-title="$filters.stringify(value)"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { ENV_TYPE } from '@tarojs/taro';
import { useState } from '@taro-hooks/core';
import { escapeState } from '@taro-hooks/shared';
import { useToast, useVideo, useEnv } from 'taro-hooks';

const videoId = 'demo-video-id';
const env = useEnv();
const [videoInfo, setVideoInfo] =
  useState<Taro.chooseVideo.SuccessCallbackResult>();
const [videoSummary, setVideoSummary] =
  useState<Taro.getVideoInfo.SuccessCallbackResult>();

const [videoContext, { choose, chooseMedia, open, save, compress, get }] =
  useVideo(videoId, {
    camera: 'back',
    sourceType: ['camera', 'album'],
  });

const { show } = useToast({
  title: 'initial title',
  duration: 500,
  mask: true,
});

const handleChoose = async () => {
  try {
    const result = await choose();
    setVideoInfo(result);

    if (env === ENV_TYPE.WEAPP) {
      const summary = await get(result.tempFilePath);
      setVideoSummary(summary);
    }
  } catch (e) {
    show({ title: '获取视频或信息失败', icon: 'error' });
  }
};

const handleVideoAction = (action) => {
  console.log(videoContext);
  escapeState(videoContext)?.[action]?.();
};

const handleCompress = async () => {
  try {
    const { size } = await compress({ src: videoInfo?.tempFilePath });
    show({ title: `压缩: ${size}/${videoInfo?.size}` });
  } catch (e) {
    show({ title: '压缩失败', icon: 'error' });
  }
};
</script>

<style>
#demo-video-id {
  position: relative;
  left: auto;
  top: auto;
  width: 100%;
  height: 200px;
}
</style>
