// ant-mobile-taro/src/components/nav-bar/nav-bar.tsx
import React, { FC, ReactNode } from 'react'
import classNames from 'classnames'
import { View, Text } from '@tarojs/components'
import { Left } from 'ant-mobile-icon-taro/es/index.react'
import { NativeProps, withNativeProps } from '../../utils/native-props'
import { mergeProps } from '../../utils/with-default-props'

const classPrefix = `adm-nav-bar`

export type NavBarProps = {
  back?: string | null
  backArrow?: boolean | ReactNode
  left?: ReactNode
  right?: ReactNode
  onBack?: () => void
} & NativeProps<'--height' | '--border-bottom'>

const defaultProps = {
  back: '',
  backArrow: true,
}
export const NavBar: FC<NavBarProps> = p => {
  const props = mergeProps(defaultProps, p)
  const { back, backArrow } = props

  return withNativeProps(
    props,
    <View className={classNames(classPrefix)}>
      <View className={`${classPrefix}-left`} role='button'>
        {back !== null && (
          <View className={`${classPrefix}-back`} onClick={props.onBack}>
            {backArrow && (
              <Text className={`${classPrefix}-back-arrow`}>
                {backArrow === true ? <Left /> : backArrow}
              </Text>
            )}
            <Text aria-hidden='true'>{back}</Text>
          </View>
        )}
        {props.left}
      </View>
      <View className={`${classPrefix}-title`}>{props.children}</View>
      <View className={`${classPrefix}-right`}>{props.right}</View>
    </View>
  )
}

// packages/app-vue/src/pages/NavBar/index.tsx
import { defineComponent } from 'vue';
import { showToast } from '@tarojs/taro';
import { NavBar, Space } from 'ant-mobile-taro';
import { View } from '@tarojs/components';
import DemoBlock from '@components/DemoBlock/index.vue';
import { Search, Dash, Close } from 'ant-mobile-icon-taro/es/index.vue';

import './index.less';

export default defineComponent({
  name: 'NavBarDemo',
  setup() {
    const right = (
      <View style={{ fontSize: 18 }}>
        <Space>
          <Search />
          <Dash />
        </Space>
      </View>
    );

    const back = () =>
      showToast({
        title: '点击了返回区域',
        duration: 1000,
      });

    return () => (
      <>
        <DemoBlock title="基础使用" padding="0">
          <NavBar onBack={back}>标题</NavBar>
        </DemoBlock>

        <DemoBlock title="自定义返回按钮的文字" padding="0">
          <NavBar back="返回" onBack={back}>
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="返回按钮不显示图标" padding="0">
          <NavBar back="返回" onBack={back} backArrow={false}>
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义返回按钮图标" padding="0">
          <NavBar onBack={back}>
            {{
              default: () => '标题',
              back: () => '返回',
              backArrow: (props) => <Close {...props} />,
            }}
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义左侧区域" padding="0">
          <NavBar back="返回" onBack={back} left="关闭">
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义右侧区域" padding="0">
          <NavBar right={right} onBack={back}>
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义标题内容" padding="0">
          <NavBar onBack={back}>
            <View>
              <View>标题</View>
              <View className="my-nav-bar-subtitle">副标题</View>
            </View>
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义高度和下边框" padding="0">
          <NavBar
            style={{
              '--height': '36px',
              '--border-bottom': '1px #eee solid',
            }}
            onBack={back}
          >
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="标题超长自动省略" padding="0">
          <NavBar onBack={back}>这是一条很长很长很长很长很长很长的标题</NavBar>
        </DemoBlock>
      </>
    );
  },
});
