// ant-mobile-taro/src/components/index-bar/index-bar.vue.tsx
/* eslint-disable react/react-in-jsx-scope */
import { ref, watchEffect, h, VNode, onMounted } from 'vue'
import classNames from 'classnames'
import { ScrollView, View } from '@tarojs/components'
import { ISetupContext, withNativeProps } from '../../utils/native-props.vue'
import { throttle } from 'lodash-wechat'
import { Sidebar } from './sidebar.vue'
import { convertPx } from '../../utils/convert-px'
import { devWarning } from '../../utils/dev-log'
import { getComputedStyle } from '../../utils/get-client-rect'
import { escapeUnit, getVueChildren, getVueElement } from '../../utils/tool'
import { nextTick } from '@tarojs/taro'

const classPrefix = `adm-index-bar`

export const IndexBarProps = {
  sticky: {
    type: Boolean,
    default: true,
  },
  height: {
    type: [String, Number],
    default: '100vh',
  },
}

export type IndexBarRef = {
  scrollTo: (index: string) => void
}

export const IndexBar = withNativeProps({
  name: 'IndexBar',
  props: IndexBarProps,
  setup(props, { attrs, slots }: ISetupContext<'--sticky-offset-top'>) {
    const titleHeight = convertPx(35)
    const bodyRef = ref<VNode>()
    const indexes = ref<string[]>([])
    const panels = ref<VNode[]>([])
    const offsetTopMap = ref<{ offsetTop: number; clientHeight: number }[]>([])
    const offsetTop = ref(0)
    const activeIndex = ref<string>()

    watchEffect(() => {
      nextTick(async () => {
        if (indexes.value.length) {
          const fields = (await getComputedStyle(
            `.${classPrefix}-anchor`,
            ['height'],
            true
          )) as any[]
          // eval : index + above
          const anchorOffsetTop = fields
            .map(({ height }) => Number(escapeUnit(height)))
            .filter(v => !isNaN(v))
            .map((v, i, self) => {
              if (i === 0) {
                return { offsetTop: 0, clientHeight: v }
              } else {
                const above = self.slice(0, i).filter(v => !isNaN(v))
                return {
                  offsetTop: above.reduce((pre, cur) => pre + cur, 0),
                  clientHeight: v,
                }
              }
            })
          anchorOffsetTop.length && (offsetTopMap.value = anchorOffsetTop)
        }
      })
    })

    async function scrollTo(index: string) {
      const body = bodyRef.value
      if (!body) return

      const children = getVueChildren(body)

      for (let i = 0; i < children.length; i++) {
        const panel = (
          children.item ? children.item(i) : children[i]
        ) as HTMLElement
        if (!panel) continue

        const panelIndex = panel.dataset['index']
        const panelOffsetTop = panel.offsetTop ?? panel.dataset['offsetTop']
        if (panelIndex === index) {
          offsetTop.value = panelOffsetTop
          console.log('change', index, panelOffsetTop, panel)
          activeIndex.value = index
          return
        }
      }
    }

    const checkActiveIndex = throttle(({ detail: { scrollTop } }) => {
      const body = bodyRef.value
      if (!body) return

      const elements = getVueElement(body).getElementsByClassName(
        `${classPrefix}-anchor`
      )
      for (let i = 0; i < elements.length; i++) {
        const panel = (
          elements.item ? elements.item(i) : elements[i]
        ) as HTMLElement
        if (!panel) continue
        const panelIndex = panel.dataset['index']
        if (!panelIndex) continue
        const panelScrollTop = panel.offsetTop ?? panel.dataset['offsetTop']
        const panelClientHeight =
          panel.clientHeight ?? panel.dataset['clientHeight']
        if (panelScrollTop + panelClientHeight - titleHeight > scrollTop) {
          activeIndex.value = panelIndex
          return
        }
      }
    }, 100)

    const RenderScrollViewItems = withNativeProps({
      name: 'RenderScrollViewItems',
      setup() {
        return () => (
          <>
            {slots.default?.()?.[0] &&
              (slots.default()[0].children as VNode[]).map((child, idx) => {
                if (typeof child !== 'object') return null
                // @ts-ignore
                if (child?.type?.name !== 'Panel') {
                  devWarning(
                    'IndexBar',
                    'The children of `IndexBar` must be `IndexBar.Panel` components.'
                  )
                  return null
                }
                indexes.value[idx] = child?.props?.index
                const renderPanel = h(
                  <View
                    key={child?.props?.index}
                    id={`index-bar-index-${child?.props?.index}`}
                    data-index={child?.props?.index}
                    className={`${classPrefix}-anchor`}
                    data-client-height={
                      offsetTopMap.value[idx]?.clientHeight ?? 0
                    }
                    data-offset-top={offsetTopMap.value[idx]?.offsetTop ?? 0}
                  >
                    <View className={`${classPrefix}-anchor-title`}>
                      {child?.props?.title || child?.props?.index}
                    </View>
                    {child.children?.default?.()}
                  </View>,
                  { ...child?.props }
                )
                panels.value[idx] = renderPanel
                return renderPanel
              })}
          </>
        )
      },
    })

    return () => (
      <View
        className={classNames(
          `${classPrefix}`,
          {
            [`${classPrefix}-sticky`]: props.sticky,
          },
          attrs.class,
          attrs.className
        )}
        style={{ height: props.height }}
      >
        <Sidebar
          indexes={indexes.value}
          activeIndex={activeIndex.value ?? indexes.value[0] ?? ''}
          onActive={(index: string) => {
            scrollTo(index)
          }}
        />
        <ScrollView
          scrollY
          ref={bodyRef}
          className={`${classPrefix}-body`}
          scrollTop={offsetTop.value}
          style={{ height: props.height }}
          onScroll={checkActiveIndex}
        >
          <RenderScrollViewItems />
        </ScrollView>
      </View>
    )
  },
})

// ant-mobile-taro/src/components/index-bar/index-bar.tsx
import React, {
  forwardRef,
  useRef,
  useState,
  useImperativeHandle,
  ReactElement,
  useLayoutEffect,
} from 'react'
import classNames from 'classnames'
import { ScrollView, View } from '@tarojs/components'
import { NativeProps, withNativeProps } from '../../utils/native-props'
import { useThrottleFn } from 'ahooks'
import { mergeProps } from '../../utils/with-default-props'
import { Sidebar } from './sidebar'
import { convertPx } from '../../utils/convert-px'
import { Panel } from './panel'
import { devWarning } from '../../utils/dev-log'
import { getComputedStyle } from '../../utils/get-client-rect'
import { escapeUnit } from '../../utils/tool'
import { nextTick } from '@tarojs/taro'

const classPrefix = `adm-index-bar`

export type IndexBarProps = {
  sticky?: boolean
  children?: React.ReactNode
  height?: string | number
} & NativeProps<'--sticky-offset-top'>

export type IndexBarRef = {
  scrollTo: (index: string) => void
}

const defaultProps = {
  sticky: true,
  height: '100vh',
}

export const IndexBar = forwardRef<IndexBarRef, IndexBarProps>((p, ref) => {
  const props = mergeProps(defaultProps, p)
  const titleHeight = convertPx(35)
  const bodyRef = useRef<HTMLDivElement>(null)

  const indexes: string[] = []
  const panels: ReactElement[] = []
  const [offsetTopMap, setOffsetTopMap] = useState<
    { offsetTop: number; clientHeight: number }[]
  >([])
  const offsetTop = useRef<number>(0)

  React.Children.forEach(props.children, (child, idx) => {
    if (!React.isValidElement(child)) return
    if (child.type !== Panel) {
      devWarning(
        'IndexBar',
        'The children of `IndexBar` must be `IndexBar.Panel` components.'
      )
      return
    }
    indexes.push(child.props.index)
    panels.push(
      withNativeProps(
        child.props,
        <View
          key={child.props.index}
          id={`index-bar-index-${child.props.index}`}
          data-index={child.props.index}
          className={`${classPrefix}-anchor`}
          data-client-height={offsetTopMap[idx]?.clientHeight ?? 0}
          data-offset-top={offsetTopMap[idx]?.offsetTop ?? 0}
        >
          <View className={`${classPrefix}-anchor-title`}>
            {child.props.title || child.props.index}
          </View>
          {child.props.children}
        </View>
      )
    )
  })

  const [activeIndex, setActiveIndex] = useState(indexes[0])

  useImperativeHandle(ref, () => ({ scrollTo }))

  useLayoutEffect(() => {
    nextTick(caculateRectWithOffsetAndClient)
  }, [props.children])

  // miniprograme do not exist offsetTop, use rect instand
  async function caculateRectWithOffsetAndClient() {
    if (indexes.length) {
      const fields = (await getComputedStyle(
        `.${classPrefix}-anchor`,
        ['height'],
        true
      )) as any[]
      // eval : index + above
      const anchorOffsetTop = fields
        .map(({ height }) => Number(escapeUnit(height)))
        .filter(v => !isNaN(v))
        .map((v, i, self) => {
          if (i === 0) {
            return { offsetTop: 0, clientHeight: v }
          } else {
            const above = self.slice(0, i).filter(v => !isNaN(v))
            return {
              offsetTop: above.reduce((pre, cur) => pre + cur, 0),
              clientHeight: v,
            }
          }
        })
      setOffsetTopMap(anchorOffsetTop)
    }
  }

  async function scrollTo(index: string) {
    const body = bodyRef.current
    if (!body) return

    const children = body.children

    for (let i = 0; i < children.length; i++) {
      const panel = (
        children.item ? children.item(i) : children[i]
      ) as HTMLElement
      if (!panel) continue

      const panelIndex = panel.dataset['index']
      const panelOffsetTop = panel.offsetTop ?? panel.dataset['offsetTop']
      if (panelIndex === index) {
        offsetTop.current = panelOffsetTop
        console.log('change', index, panelOffsetTop, panel)
        setActiveIndex(index)
        return
      }
    }
  }

  const { run: checkActiveIndex } = useThrottleFn(
    ({ detail: { scrollTop } }) => {
      const body = bodyRef.current

      if (!body) return

      const elements = body.getElementsByClassName(`${classPrefix}-anchor`)
      for (let i = 0; i < elements.length; i++) {
        const panel = (
          elements.item ? elements.item(i) : elements[i]
        ) as HTMLElement
        if (!panel) continue
        const panelIndex = panel.dataset['index']
        if (!panelIndex) continue
        const panelScrollTop = panel.offsetTop ?? panel.dataset['offsetTop']
        const panelClientHeight =
          panel.clientHeight ?? panel.dataset['clientHeight']
        if (panelScrollTop + panelClientHeight - titleHeight > scrollTop) {
          setActiveIndex(panelIndex)
          return
        }
      }
    },
    { wait: 100, trailing: true, leading: true }
  )

  return withNativeProps(
    props,
    <View
      className={classNames(`${classPrefix}`, {
        [`${classPrefix}-sticky`]: props.sticky,
      })}
      style={{ height: props.height }}
    >
      <Sidebar
        indexes={indexes}
        activeIndex={activeIndex}
        onActive={index => {
          scrollTo(index)
        }}
      />
      <ScrollView
        scrollY
        className={`${classPrefix}-body`}
        ref={bodyRef}
        scrollTop={offsetTop.current}
        style={{ height: props.height }}
        onScroll={checkActiveIndex}
      >
        {panels}
      </ScrollView>
    </View>
  )
})
