// examples/taro-hooks-plugin/src/pages/wechat/useAccountInfo/index.tsx
import React from 'react';
import { useAccountInfo } from 'taro-hooks';

import DemoContent from '@src/components/DemoContent';
import { Cell } from '@taroify/core';

export default () => {
  const accountInfo = useAccountInfo();

  return (
    <DemoContent>
      {Object.keys(accountInfo).length ? (
        Object.entries(accountInfo).map(([key, value]) => {
          return (
            <Cell.Group clickable title={key} key={key}>
              {typeof value === 'string' ? (
                <Cell key={key} title={'小程序 - ' + key}>
                  {value}
                </Cell>
              ) : (
                Object.entries(value as {}).map(([subKey, subValue]) => (
                  <Cell key={subKey} title={'小程序 - ' + subKey}>
                    {subValue}
                  </Cell>
                ))
              )}
            </Cell.Group>
          );
        })
      ) : (
        <Cell>暂无信息</Cell>
      )}
    </DemoContent>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/wechat/useAccountInfo/index.vue
<template>
  <demo-content>
    <nut-cell v-if="!emptyInfo">暂无信息</nut-cell>
    <template v-else>
      <nut-cell-group
        v-for="(value, key) in accountInfo"
        :title="'小程序 - ' + key"
        :key="key"
      >
        <nut-cell
          v-if="typeof value === 'string'"
          :title="'小程序 - ' + key"
          :desc="value"
        ></nut-cell>
        <nut-cell
          v-else
          v-for="(subValue, subKey) in value"
          :key="subKey"
          :title="'小程序 - ' + subKey"
          :desc="subValue"
        ></nut-cell>
      </nut-cell-group>
    </template>
  </demo-content>
</template>

<script setup lang="ts">
import { useAccountInfo } from 'taro-hooks';

const accountInfo = useAccountInfo();

const emptyInfo = Object.keys(accountInfo)?.length;
</script>
