// examples/taro-hooks-plugin-vue/src/pages/device/useBluetooth/index.vue
<template>
  <demo-content>
    <nut-cell-group title="适配器">
      <nut-cell
        v-for="(value, key) in adapter ?? {}"
        :key="key"
        :title="key"
        :sub-title="$filters.stringify(value)"
      ></nut-cell>
    </nut-cell-group>
    <nut-divider>设备</nut-divider>
    <nut-cell-group
      v-for="(item, key) in devices"
      :key="key"
      :title="item.name"
    >
      <nut-cell
        v-for="(value, itemKey) in item"
        :key="itemKey"
        :title="itemKey"
        :sub-title="$filters.stringify(value)"
      ></nut-cell>
    </nut-cell-group>
    <nut-divider>连接设备</nut-divider>
    <nut-cell-group
      v-for="(item, key) in connectedDevices"
      :key="key"
      :title="item.name"
    >
      <nut-cell
        v-for="(value, itemKey) in item"
        :key="itemKey"
        :title="itemKey"
        :sub-title="$filters.stringify(value)"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useBluetooth } from 'taro-hooks';

const [{ devices, connectedDevices, adapter }] = useBluetooth();
</script>

// examples/taro-hooks-plugin/src/pages/device/useBluetooth/index.tsx
import React from 'react';
import { useBluetooth } from 'taro-hooks';
import DemoContent from '@src/components/DemoContent';
import { Cell, Divider } from '@taroify/core';

export default () => {
  const [{ devices, connectedDevices, adapter }] = useBluetooth();

  return (
    <DemoContent>
      <Cell.Group title="适配器">
        {Object.entries(adapter ?? {}).map(([key, value]) => (
          <Cell key={key} title={key} brief={JSON.stringify(value)}></Cell>
        ))}
      </Cell.Group>
      <Divider>设备</Divider>
      {devices.map((item, key) => (
        <Cell.Group title={item.name} key={key}>
          {Object.entries(item).map(([itemKey, value]) => (
            <Cell
              key={itemKey}
              title={itemKey}
              brief={JSON.stringify(value)}
            ></Cell>
          ))}
        </Cell.Group>
      ))}
      <Divider>连接设备</Divider>
      {connectedDevices.map((item, key) => (
        <Cell.Group title={item.name} key={key}>
          {Object.entries(item).map(([itemKey, value]) => (
            <Cell
              key={itemKey}
              title={itemKey}
              brief={JSON.stringify(value)}
            ></Cell>
          ))}
        </Cell.Group>
      ))}
    </DemoContent>
  );
};
