// examples/taro-hooks-plugin/src/pages/network/useRequest/polling/index.tsx
import React from 'react';
import DemoContent from '@src/components/DemoContent';
import { Button, Flex, Field } from '@taroify/core';

import { useRequest } from 'taro-hooks';
import Mock from 'mockjs';

function getUsername(): Promise<string> {
  console.log('polling getUsername');
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock('@name()'));
    }, 1000);
  });
}

export default () => {
  const { data, loading, run, cancel } = useRequest(getUsername, {
    pollingInterval: 1000,
    pollingWhenHidden: false,
  });

  return (
    <DemoContent title="轮询">
      <Field align="start">Username: {loading ? 'Loading' : data}</Field>
      <Flex align="center" gutter={10}>
        <Flex.Item span={12}>
          <Button
            loading={loading}
            color="primary"
            size="small"
            block
            onClick={run}
          >
            start
          </Button>
        </Flex.Item>
        <Flex.Item span={12}>
          <Button color="danger" size="small" block onClick={cancel}>
            stop
          </Button>
        </Flex.Item>
      </Flex>
    </DemoContent>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/network/useRequest/polling/index.vue
<template>
  <block>
    <demo-content title="轮询">
      <view>Username: {{ request.loading ? 'Loading...' : request.data }}</view>
      <nut-row justify="space-between">
        <nut-col :span="11">
          <nut-button
            :loading="request.loading"
            size="small"
            type="primary"
            shape="square"
            block
            @click="request.run()"
          >
            run
          </nut-button>
        </nut-col>
        <nut-col :span="11">
          <nut-button
            :loading="request.loading"
            size="small"
            type="danger"
            shape="square"
            block
            @click="request.cancel()"
          >
            stop
          </nut-button>
        </nut-col>
      </nut-row>
    </demo-content>
  </block>
</template>

<script>
import { useRequest } from 'taro-hooks';

import Mock from 'mockjs';

function getUsername() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock('@name()'));
    }, 1000);
  });
}
export default {
  setup() {
    const request = useRequest(getUsername, {
      pollingInterval: 1000,
      pollingWhenHidden: false,
    });

    return { request };
  },
};
</script>
