// packages/app/src/pages/useRequest/mutate/index.tsx
/**
 * desc: 你可以通过 `mutate` ，直接修改 `data` 。 `mutate` 函数参数可以为 `newData` 或 `(oldData)=> newData` 。
 */
import React, { useState } from 'react';
import { useRequest } from 'taro-hooks';
import Mock from 'mockjs';

import { AtInput, AtButton } from 'taro-ui';
import { View } from '@tarojs/components';
import DocPage from '@components/DocPage';

import 'taro-ui/dist/style/components/icon.scss';

function getUsername(): Promise<string> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock('@name()'));
    }, 1000);
  });
}

const MutateRequest = () => {
  const [state, setState] = useState('');
  const { data, mutate, loading } = useRequest(getUsername, {
    onSuccess: (result: string) => {
      setState(result);
    },
  });

  return (
    <DocPage title="useRequest 请求" panelTitle="突变">
      <View>username: {data}</View>
      <AtInput
        name="username"
        onChange={(e) => setState(e as string)}
        value={state}
        placeholder="Please enter username"
      />
      <AtButton type="primary" loading={loading} onClick={() => mutate(state)}>
        {loading ? 'loading' : 'Edit'}
      </AtButton>
    </DocPage>
  );
};

export default MutateRequest;

// examples/taro-hooks-plugin-vue/src/pages/network/useRequest/basic/mutate.vue
<template>
  <block>
    <demo-content title="Basic - 立即变更数据" desc="修改用户名称">
      <view>Username: {{ getUserNameRequest.data }}</view>
      <nut-input
        :disabled="editUserNameRequest.loading"
        v-model="state"
        placeholder="Please enter username"
      >
        <template #button>
          <nut-button
            :loading="editUserNameRequest.loading"
            size="small"
            type="primary"
            shape="square"
            @click="onChange()"
            >{{ editUserNameRequest.loading ? 'Loading' : 'Edit' }}</nut-button
          >
        </template>
      </nut-input>
    </demo-content>
  </block>
</template>

<script>
import { showToast } from '@tarojs/taro';
import { useRef, useState } from '@taro-hooks/core';
import { useRequest } from 'taro-hooks';
import { escapeState } from '@taro-hooks/shared';

import Mock from 'mockjs';

function getUsername(id) {
  console.log('use-request-refresh-id', id);
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(Mock.mock('@name()'));
    }, 1000);
  });
}

function editUsername() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (Math.random() > 0.5) {
        resolve();
      } else {
        reject(new Error('Failed to modify username'));
      }
    }, 1000);
  });
}

export default {
  setup() {
    // store last username
    const lastRef = useRef();

    const [state, setState] = useState('');

    // get username
    const getUserNameRequest = useRequest(getUsername);

    // edit username
    const editUserNameRequest = useRequest(editUsername, {
      manual: true,
      onSuccess: (result, params) => {
        setState('');
        showToast({
          icon: 'success',
          title: `The username was changed to "${params[0]}" !`,
        });
      },
      onError: (error) => {
        showToast({
          icon: 'error',
          title: error.message,
        });
        const { mutate } = escapeState(getUserNameRequest);
        mutate(lastRef.current);
      },
    });

    const onChange = () => {
      const { data, mutate } = escapeState(getUserNameRequest);
      const { run } = escapeState(editUserNameRequest);
      const username = escapeState(state);
      lastRef.current = data;
      mutate(username);
      run(username);
    };

    return { getUserNameRequest, editUserNameRequest, state, onChange };
  },
};
</script>
