// examples/taro-hooks-plugin/src/pages/network/useRequest/basic/refresh.tsx
import React from 'react';
import { View } from '@tarojs/components';
import DemoContent from '@src/components/DemoContent';
import { Button } from '@taroify/core';

import { useEffect } from '@taro-hooks/core';
import { useRequest } from 'taro-hooks';
import Mock from 'mockjs';

function getUsername(id: number): Promise<string> {
  console.log('use-request-refresh-id', id);
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock('@name()'));
    }, 1000);
  });
}

export default () => {
  const { data, loading, run, refresh } = useRequest(
    (id: number) => getUsername(id),
    {
      manual: true,
    },
  );

  useEffect(() => {
    run(1);
  }, []);

  return (
    <DemoContent title="Basic - 刷新（重复上一次请求）" desc="刷新用户名称">
      {loading ? (
        <View>Loading...</View>
      ) : (
        <>
          <View>Username: {data}</View>
          <Button
            disabled={loading}
            loading={loading}
            color="primary"
            size="small"
            onClick={refresh}
          >
            {loading ? 'Loading' : 'Refresh'}
          </Button>
        </>
      )}
    </DemoContent>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/network/useRequest/basic/refresh.vue
<template>
  <block>
    <demo-content title="Basic - 刷新（重复上一次请求）" desc="刷新用户名称">
      <view v-if="request.loading"> loading... </view>
      <template v-else>
        <view v-if="request.error"> error: {{ request.error.message }} </view>
        <view v-else> Username: {{ request.data }} </view>
      </template>
      <nut-button
        :loading="request.loading"
        size="small"
        type="primary"
        shape="square"
        @click="request.refresh()"
        >{{ request.loading ? 'Loading' : 'Refresh' }}</nut-button
      >
    </demo-content>
  </block>
</template>

<script>
import { useEffect } from '@taro-hooks/core';
import { useRequest } from 'taro-hooks';
import { escapeState } from '@taro-hooks/shared';

import Mock from 'mockjs';

function getUsername(id) {
  console.log('use-request-refresh-id', id);
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(Mock.mock('@name()'));
    }, 1000);
  });
}
export default {
  setup() {
    const request = useRequest((id) => getUsername(id), {
      manual: true,
    });

    useEffect(() => {
      escapeState(request).run(1);
    }, []);

    return { request };
  },
};
</script>
