// ant-mobile-taro/src/components/grid/grid.vue.tsx
/* eslint-disable react/react-in-jsx-scope */
import { toRefs, computed } from 'vue'
import classNames from 'classnames'
import { ITouchEvent, View } from '@tarojs/components'
import { ISetupContext, withNativeProps } from '../../utils/native-props.vue'
import { toCSSLength } from '../../utils/to-css-length'

const classPrefix = `adm-grid`

const GridProps = {
  columns: Number,
  gap: {
    validator(value: number | string | [number | string, number | string]) {
      return (
        ['string', 'number'].includes(typeof value) ||
        (Array.isArray(value) &&
          value.every(v => ['string', 'number'].includes(typeof v)))
      )
    },
  },
}

export const Grid = withNativeProps({
  name: 'Grid',
  props: GridProps,
  setup(
    props,
    {
      attrs,
      slots,
    }: ISetupContext<
      '--gap' | '--gap-vertical' | '--gap-horizontal' | '--columns'
    >
  ) {
    const { gap, columns } = toRefs(props)
    const { style } = attrs
    const gridStyle = computed(() => {
      const computedStyle = {
        ...style,
        '--columns': columns?.value?.toString(),
      }
      if (gap?.value !== undefined) {
        if (Array.isArray(gap.value)) {
          computedStyle['--gap-horizontal'] = toCSSLength(gap.value[0])
          computedStyle['--gap-vertical'] = toCSSLength(gap.value[1])
        } else {
          computedStyle['--gap'] = toCSSLength(gap.value as string | number)
        }
      }

      return computedStyle
    })
    return () => (
      <View
        className={classNames(classPrefix, attrs.class, attrs.className)}
        style={gridStyle.value}
      >
        {slots.default && slots.default()}
      </View>
    )
  },
})

const GridItemProps = {
  span: {
    type: Number,
    default: 1,
  },
}

export const GridItem = withNativeProps({
  name: 'GridItem',
  props: GridItemProps,
  emits: ['click'],
  setup(props, { attrs, emit, slots }: ISetupContext<'--item-span'>) {
    const handleClick = (event: ITouchEvent) => {
      emit('click', event)
    }
    const itemStyle = {
      ...attrs.style,
      '--item-span': props.span,
    }
    return () => (
      <View
        className={classNames(
          `${classPrefix}-item`,
          attrs.class,
          attrs.className
        )}
        style={itemStyle}
        onClick={handleClick}
      >
        {slots.default && slots.default()}
      </View>
    )
  },
})

// ant-mobile-taro/src/components/grid/grid.tsx
import React, { FC } from 'react'
import { ITouchEvent, View } from '@tarojs/components'
import { NativeProps, withNativeProps } from '../../utils/native-props'
import { toCSSLength } from '../../utils/to-css-length'
import { mergeProps } from '../../utils/with-default-props'

const classPrefix = `adm-grid`

export type GridProps = {
  columns: number
  gap?: number | string | [number | string, number | string]
} & NativeProps<'--gap' | '--gap-vertical' | '--gap-horizontal'>

export const Grid: FC<GridProps> = props => {
  const style: GridProps['style'] & Record<'--columns', string> = {
    '--columns': props.columns.toString(),
  }
  const { gap } = props
  if (gap !== undefined) {
    if (Array.isArray(gap)) {
      style['--gap-horizontal'] = toCSSLength(gap[0])
      style['--gap-vertical'] = toCSSLength(gap[1])
    } else {
      style['--gap'] = toCSSLength(gap)
    }
  }

  return withNativeProps(
    props,
    <View className={classPrefix} style={style}>
      {props.children}
    </View>
  )
}

export type GridItemProps = {
  span?: number
  onClick?: (event: ITouchEvent) => void
} & NativeProps

type GridItemStyle = React.CSSProperties &
  Record<'--item-span', GridItemProps['span']>

export const GridItem: FC<GridItemProps> = p => {
  const props = mergeProps({ span: 1 }, p)

  const itemStyle: GridItemStyle = {
    '--item-span': props.span,
  }
  return withNativeProps(
    props,
    <View
      className={`${classPrefix}-item`}
      style={itemStyle}
      onClick={props.onClick}
    >
      {props.children}
    </View>
  )
}
