// examples/taro-hooks-plugin-vue/src/pages/media/useImage/index.vue
<template>
  <demo-content>
    <nut-swiper height="200" class="demo-swiper gap">
      <nut-swiper-item
        v-for="(url, index) in fileInfo?.tempFilePaths"
        :key="index"
      >
        <image class="demo-swiper-item" :src="url"></image>
      </nut-swiper-item>
    </nut-swiper>
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="choose()"
      >选择图片</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="preview({ urls: fileInfo?.tempFilePaths })"
      >预览照片</nut-button
    >
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="save(fileInfo?.tempFilePaths?.[0])"
      >保存照片</nut-button
    >
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="handleGetFileInfo()"
      >获取图片信息</nut-button
    >
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="choose({}, true)"
      >获取会话文件(仅小程序)</nut-button
    >
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="edit(fileInfo?.tempFilePaths?.[0])"
      >编辑图片(仅小程序)</nut-button
    >
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="
        previewMedia({ sources: [{ url: fileInfo?.tempFilePaths?.[0] }] })
      "
      >预览媒体(仅小程序)</nut-button
    >
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="handleCompress()"
      >压缩图片</nut-button
    >
    <nut-cell-group title="图片信息">
      <nut-cell
        v-for="(value, key) in imageInfo"
        :key="key"
        :title="key"
        :sub-title="$filters.stringify(value)"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useTaroState } from '@tarojs/taro';
import { escapeState } from '@taro-hooks/shared';
import { useToast, useImage } from 'taro-hooks';

const { show } = useToast({ title: 'useImage', mask: true });
const [imageInfo, setImageInfo] =
  useTaroState<Taro.getImageInfo.SuccessCallbackResult>();
const [fileInfo, { choose, compress, get, preview, previewMedia, save, edit }] =
  useImage({
    count: 15,
  });

const handleGetFileInfo = async () => {
  try {
    const info = await get(escapeState(fileInfo)?.tempFilePaths?.[0]);
    setImageInfo(info);
  } catch (e) {
    show({
      title: '获取信息失败',
      icon: 'error',
    });
  }
};

const handleCompress = async () => {
  try {
    const info = await compress(escapeState(fileInfo)?.tempFilePaths?.[0]);
    setImageInfo(info);
  } catch (e) {
    show({
      title: '压缩失败',
      icon: 'error',
    });
  }
};
</script>

<style>
.demo-swiper,
.demo-swiper-item {
  height: 200px;
}
.nut-swiper-item {
  text-align: center;
}
</style>

// packages/app/src/pages/useImage/index.tsx
import React, { useCallback, useState } from 'react';
import { AtButton, AtFloatLayout, AtList, AtListItem } from 'taro-ui';
import DocPage from '@components/DocPage';
import { Swiper, SwiperItem, Image } from '@tarojs/components';

import { useImage, useEnv, useToast } from 'taro-hooks';
import { ENV_TYPE } from '@tarojs/taro';

import './index.less';

export default () => {
  const [show] = useToast({ mask: true });
  const [open, changeOpen] = useState<boolean>(false);
  const [imageInfo, setImageInfo] = useState({});
  const env = useEnv();
  const [
    fileInfo,
    { choose, chooseMessageFile, preview, save, getInfo, compress },
  ] = useImage({
    count: 15,
  });

  const getImageInfo = useCallback(
    async (src: string) => {
      const info = await getInfo(src);
      setImageInfo(info);
      changeOpen(true);
    },
    [getInfo],
  );

  const getMessageFileInfo = useCallback(async () => {
    const info = await chooseMessageFile(1);
    setImageInfo(info.tempFiles[0]);
    changeOpen(true);
  }, [chooseMessageFile]);

  const compressInfo = useCallback(
    async (src: string) => {
      const info = await compress(src);
      setImageInfo(info);
      changeOpen(true);
    },
    [compress],
  );

  const saveInfo = useCallback(() => {
    save(fileInfo.tempFilePaths[0])
      .then(() => {
        show({
          title: '保存成功',
        });
      })
      .catch(() => {
        show({
          title: '保存失败',
        });
      });
  }, [save, fileInfo, show]);

  return (
    <>
      <DocPage title="useImage 图片" panelTitle="useImage">
        <Swiper className="taro-hooks-swiper" autoplay>
          {(fileInfo.tempFilePaths || []).map((v: string) => (
            <SwiperItem key={v}>
              <Image className="taro-hooks-image" mode="aspectFit" src={v} />
            </SwiperItem>
          ))}
        </Swiper>
        <AtButton onClick={() => choose()}>选择图片</AtButton>
        <AtButton
          disabled={!fileInfo.tempFilePaths}
          className="gap"
          onClick={() => preview({ urls: fileInfo.tempFilePaths })}
        >
          预览照片
        </AtButton>
        <AtButton disabled={!fileInfo.tempFilePaths} onClick={saveInfo}>
          保存图片
        </AtButton>
        <AtButton
          className="gap"
          disabled={!fileInfo.tempFilePaths}
          onClick={() => getImageInfo(fileInfo.tempFilePaths[0])}
        >
          获取图片信息
        </AtButton>
        <AtButton
          disabled={env !== ENV_TYPE.WEAPP}
          onClick={getMessageFileInfo}
        >
          获取会话文件(仅小程序)
        </AtButton>
        <AtButton
          className="gap"
          disabled={!fileInfo.tempFilePaths}
          onClick={() => compressInfo(fileInfo.tempFilePaths[0])}
        >
          压缩图片
        </AtButton>
        <AtFloatLayout isOpened={open} onClose={() => changeOpen(false)}>
          <AtList>
            {Object.entries(imageInfo).map(([key, value]) => (
              <AtListItem key={key} title={key} note={String(value)} />
            ))}
          </AtList>
        </AtFloatLayout>
      </DocPage>
    </>
  );
};
