// examples/taro-hooks-plugin-vue/src/pages/wechat/useEnterOptions/index.vue
<template>
  <demo-content>
    <nut-cell-group>
      <nut-cell
        v-for="(value, key) in enterOptions"
        :key="key"
        :title="key"
        :desc="value"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useEnterOptions } from 'taro-hooks';

const enterOptions = useEnterOptions();
</script>

// examples/taro-hooks-plugin/src/pages/wechat/useEnterOptions/index.tsx
import React from 'react';
import { useEnterOptions } from 'taro-hooks';

import DemoContent from '@src/components/DemoContent';
import { Cell } from '@taroify/core';

export default () => {
  const enterOptions = useEnterOptions();

  return (
    <DemoContent>
      {Object.keys(enterOptions).length ? (
        <Cell.Group clickable>
          {Object.entries(enterOptions).map(([key, value]) => (
            <Cell key={key} title={key}>
              {JSON.stringify(value)}
            </Cell>
          ))}
        </Cell.Group>
      ) : (
        <Cell>暂无信息</Cell>
      )}
    </DemoContent>
  );
};
