// ant-mobile-taro/src/components/progress-bar/progress-bar.vue.tsx
/* eslint-disable react/react-in-jsx-scope */
import { View } from '@tarojs/components'
import classnames from 'classnames'
import { computed } from 'vue'
import { ISetupContext, withNativeProps } from '../../utils/native-props.vue'

const classPrefix = `adm-progress-bar`

export const ProgressBarProps = {
  percent: Number,
}

export const ProgressBar = withNativeProps({
  name: 'ProgressBar',
  props: ProgressBarProps,
  setup(props, { attrs }: ISetupContext<'--track-width' | '--fill-color'>) {
    const fillStyle = computed(() => {
      return {
        width: `${props.percent}%`,
      }
    })

    return () => (
      <View
        className={classnames(classPrefix, attrs.class, attrs.className)}
        style={attrs.style}
      >
        <View className={`${classPrefix}-trail`}>
          <View className={`${classPrefix}-fill`} style={fillStyle.value} />
        </View>
      </View>
    )
  },
})

// ant-mobile-taro/src/components/progress-bar/progress-bar.tsx
import React, { FC } from 'react'
import { View } from '@tarojs/components'
import { NativeProps, withNativeProps } from '../../utils/native-props'
import { mergeProps } from '../../utils/with-default-props'

const classPrefix = `adm-progress-bar`

export type ProgressBarProps = {
  percent?: number
} & NativeProps<'--track-width' | '--fill-color'>

export const ProgressBar: FC<ProgressBarProps> = p => {
  const props = mergeProps({ percent: 0 }, p)
  const fillStyle = {
    width: `${props.percent}%`,
  }

  return withNativeProps(
    props,
    <View className={classPrefix}>
      <View className={`${classPrefix}-trail`}>
        <View className={`${classPrefix}-fill`} style={fillStyle} />
      </View>
    </View>
  )
}
