// examples/taro-hooks-plugin/src/pages/device/useBrightness/index.tsx
import React from 'react';
import { useBrightness } from 'taro-hooks';

import DemoContent from '@src/components/DemoContent';
import { Cell, Progress, Slider } from '@taroify/core';

export default () => {
  const [brightness, setBrightness] = useBrightness();

  return (
    <DemoContent>
      <Cell.Group clickable>
        <Cell
          title="当前亮度"
          brief={<Progress percent={(brightness || 0) * 100} />}
        >
          {brightness}
        </Cell>
        <Cell
          title="设置亮度"
          brief={
            <Slider
              min={0}
              max={1}
              step={0.1}
              defaultValue={brightness || 0}
              onChange={setBrightness}
            />
          }
        ></Cell>
      </Cell.Group>
    </DemoContent>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/device/useBrightness/index.vue
<template>
  <demo-content>
    <nut-cell-group>
      <nut-cell title="当前亮度">
        <nut-progress :percentage="(brightness || 0) * 100" />
      </nut-cell>
      <nut-cell title="设置亮度">
        <nut-range
          :min="0"
          :max="1"
          :step="0.1"
          v-model="rangeBrightness"
          @change="setBrightness($event)"
        ></nut-range>
      </nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useBrightness } from 'taro-hooks';
import { useState } from '@taro-hooks/core';

const [rangeBrightness] = useState<string>();

const [brightness, setBrightness] = useBrightness();
</script>
