// packages/app/src/pages/usePromise/index.tsx
import React, { useEffect, useState } from 'react';
import { View } from '@tarojs/components';
import DocPage from '@components/DocPage';

import { usePromise } from 'taro-hooks';
import Taro, { General } from '@tarojs/taro';

export default () => {
  const makePhoneCallPromise = usePromise(
    { phoneNumber: '132111' },
    'makePhoneCall',
  );

  useEffect(() => {
    makePhoneCallPromise
      .then((res: General.CallbackResult) => {
        Taro.showModal({
          content: '拨号成功',
        });
      })
      .catch((e: any) => {
        Taro.showModal({
          content: e.errMsg,
        });
      })
      .finally((res: General.CallbackResult) => {
        console.log(res);
      });
  }, [makePhoneCallPromise]);

  return (
    <>
      <DocPage title="usePromise 异步" panelTitle="usePromise">
        <View>请观察是否吊起通话</View>
      </DocPage>
    </>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/basic/usePromise/index.vue
<template>
  <demo-content>
    <nut-button shape="square" type="primary" block @click="handleClick()"
      >Click me!</nut-button
    >
  </demo-content>
</template>

<script setup lang="ts">
import { usePromise } from 'taro-hooks';
import { showToast, makePhoneCall } from '@tarojs/taro';

type MakePhoneCallOption = Taro.makePhoneCall.Option;
type MakePhoneCallResult = TaroGeneral.CallbackResult;

const useMakePhoneCall = usePromise<MakePhoneCallOption, MakePhoneCallResult>(
  makePhoneCall,
);

const handleClick = () => {
  useMakePhoneCall({ phoneNumber: '1300000' }).then(
    () => {
      showToast({
        title: '拨号成功',
        mask: true,
        icon: 'success',
      });
    },
    ({ errMsg }) => {
      showToast({
        title: errMsg,
        mask: true,
        icon: 'error',
      });
    },
  );
};
</script>
