// examples/taro-hooks-plugin-vue/src/pages/basic/useClipboardData/index.vue
<template>
  <demo-content>
    <view>请打开F12查看console</view>
    <nut-cell
      v-for="(value, key) in SETTYPE"
      :key="key"
      :title="key"
      :sub-title="$filters.stringify(value)"
      @click="set(value)"
    ></nut-cell>
    <nut-button block @click="handleGet()">打印当前剪贴板</nut-button>
  </demo-content>
</template>

<script setup lang="ts">
import { useClipboardData } from 'taro-hooks';

const SETTYPE = {
  number: 1,
  boolean: true,
  object: { name: 'taro-hooks' },
  function: function taro() {},
  string: 'taro-hooks',
  undefined: undefined,
  null: null,
  date: new Date(),
};

const [clipboardData, { set, get }] = useClipboardData();

const handleGet = async () => {
  const clipboard = await get();
  console.log('当前剪贴板内容:', clipboardData, clipboard);
};
</script>

// examples/taro-hooks-plugin/src/pages/basic/useClipboardData/index.tsx
import React from 'react';
import DemoContent from '@src/components/DemoContent';
import { View } from '@tarojs/components';
import { Cell } from '@taroify/core';
import { useClipboardData } from 'taro-hooks';

const SETTYPE = {
  number: 1,
  boolean: true,
  object: { name: 'taro-hooks' },
  function: function taro() {},
  string: 'taro-hooks',
  undefined: undefined,
  null: null,
  date: new Date(),
};

export default () => {
  const [clipboardData, { set, get }] = useClipboardData();

  const handleGet = async () => {
    const clipboard = await get();
    console.log('当前剪贴板内容:', clipboardData, clipboard);
  };

  return (
    <DemoContent>
      <View>请打开F12查看console</View>
      <Cell.Group clickable>
        {Object.entries(SETTYPE).map(([key, value]) => (
          <Cell
            key={key}
            title={key}
            brief={JSON.stringify(value)}
            onClick={() => set(value)}
          ></Cell>
        ))}
      </Cell.Group>
      <Button block onClick={handleGet}>
        打印当前剪贴板
      </Button>
    </DemoContent>
  );
};
