// examples/taro-hooks-plugin/src/pages/basic/useWebp/index.tsx
import React from 'react';
import { useWebp } from 'taro-hooks';

import DemoContent from '@src/components/DemoContent';
import { Cell, Switch } from '@taroify/core';

export default () => {
  const canIUseWebP = useWebp();

  return (
    <DemoContent>
      <Cell.Group clickable>
        <Cell title="是否可用WebP">
          <Switch disabled checked={canIUseWebP} />
        </Cell>
      </Cell.Group>
    </DemoContent>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/basic/useWebp/index.vue
<template>
  <demo-content>
    <nut-cell-group>
      <nut-cell title="是否可用WebP">
        <template v-slot:link>
          <nut-switch disable :model-value="canIUseWebP" />
        </template>
      </nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useWebp } from 'taro-hooks';

const canIUseWebP = useWebp();
</script>
