// examples/taro-hooks-plugin-vue/src/pages/network/useRequest/refreshDeps/index.vue
<template>
  <demo-content title="依赖刷新">
    <view>School: {{ request.loading ? 'Loading...' : request.data }}</view>
    <nut-row justify="center">
      <nut-button
        :loading="request.loading"
        size="small"
        type="primary"
        shape="square"
        block
        @click="setOpen(true)"
      >
        userId: {{ userId }}(click me!)
      </nut-button>
    </nut-row>
    <nut-actionsheet
      v-model:visible="open"
      :menu-items="menuItems"
      @choose="handleChoose($event)"
    ></nut-actionsheet>
  </demo-content>
</template>

<script>
import { useRequest } from 'taro-hooks';
import { useTaroState } from '@tarojs/taro';
import { escapeState } from '@taro-hooks/shared';

const userSchool = (id) => {
  switch (id) {
    case '1':
      return 'Tsinghua University';
    case '2':
      return 'Beijing University';
    case '3':
      return 'Zhejiang University';
    default:
      return '';
  }
};

async function getUserSchool(userId) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(userSchool(userId));
    }, 1000);
  });
}

export default {
  setup() {
    const menuItems = [
      { value: '1', name: 'user 1' },
      { value: '2', name: 'user 2' },
      { value: '3', name: 'user 3' },
    ];
    const [userId, setUserId] = useTaroState('1');
    const [open, setOpen] = useTaroState(false);
    const request = useRequest(() => getUserSchool(escapeState(userId)), {
      refreshDeps: [userId],
    });

    const handleChoose = (item) => {
      setUserId(item.value);
      setOpen(false);
    };

    return { request, userId, open, handleChoose, menuItems, setOpen };
  },
};
</script>

// packages/app/src/pages/useRequest/refreshDeps/index.tsx
/**
 * desc: 当 `options.refreshDeps` 变化时，useRequest 会使用之前的参数重新执行 service。
 */
import React, { useState } from 'react';
import { useRequest } from 'taro-hooks';

import { AtButton, AtActionSheet, AtActionSheetItem } from 'taro-ui';
import { View } from '@tarojs/components';
import DocPage from '@components/DocPage';

const userSchool = (id: string) => {
  switch (id) {
    case '1':
      return 'Tsinghua University';
    case '2':
      return 'Beijing University';
    case '3':
      return 'Zhejiang University';
    default:
      return '';
  }
};

async function getUserSchool(userId: string): Promise<string> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(userSchool(userId));
    }, 1000);
  });
}

const RefreshDepsRequest = () => {
  const [userId, setUserId] = useState('1');
  const [isOpened, changeIsOpened] = useState<boolean>(false);
  const { data, loading } = useRequest(() => getUserSchool(userId), {
    refreshDeps: [userId],
  });

  return (
    <DocPage title="useRequest refreshDeps" panelTitle="refreshDeps">
      <AtButton
        type="primary"
        onClick={() => changeIsOpened(true)}
        customStyle={{ margin: '10px 0' }}
      >
        点击更改userId: {userId}
      </AtButton>
      <View>School: {loading ? 'loading' : data}</View>
      <AtActionSheet isOpened={isOpened} onClose={() => changeIsOpened(false)}>
        {['1', '2', '3'].map((v) => (
          <AtActionSheetItem
            onClick={() => {
              setUserId(v);
              changeIsOpened(false);
            }}
            key={v}
          >
            user {v}
          </AtActionSheetItem>
        ))}
      </AtActionSheet>
    </DocPage>
  );
};

export default RefreshDepsRequest;
