// examples/taro-hooks-plugin-vue/src/pages/basic/useVisible/index.vue
<template>
  <demo-content>
    <nut-steps direction="vertical" :current="subscribeList.length">
      <nut-step
        v-for="{ timestamp, status } in subscribeList"
        :key="timestamp"
        :title="timestamp + ''"
        :content="'当前状态为:' + status"
        :icon="status ? 'star-fill-n' : 'star-n'"
      ></nut-step>
    </nut-steps>
  </demo-content>
</template>

<script setup lang="ts">
import { useTaroEffect, useTaroState } from '@tarojs/taro';
import { useVisible } from 'taro-hooks';
import { escapeState } from '@taro-hooks/shared';

const visible = useVisible();
type Item = { timestamp: number; status: boolean };
const [subscribeList, setSubscribeList] = useTaroState<Item[]>([]);

useTaroEffect(() => {
  const currentList = escapeState(subscribeList);
  setSubscribeList([
    ...currentList,
    { timestamp: Date.now(), status: escapeState(visible) },
  ]);
}, [visible]);
</script>

// examples/taro-hooks-plugin/src/pages/basic/useVisible/index.tsx
import React from 'react';
import { useTaroEffect, useTaroState } from '@tarojs/taro';
import { useVisible } from 'taro-hooks';
import { escapeState } from '@taro-hooks/shared';
import DemoContent from '@src/components/DemoContent';
import { View } from '@tarojs/components';
import { Steps } from '@taroify/core';
import { StarOutlined, Star } from '@taroify/icons';

type Item = { timestamp: number; status: boolean };
export default () => {
  const visible = useVisible();

  const [subscribeList, setSubscribeList] = useTaroState<Item[]>([]);

  useTaroEffect(() => {
    const currentList = escapeState(subscribeList);
    setSubscribeList([
      ...currentList,
      { timestamp: Date.now(), status: escapeState(visible) },
    ]);
  }, [visible]);

  return (
    <DemoContent>
      <Steps value={subscribeList.length - 1} direction="vertical">
        {subscribeList.map(({ timestamp, status }) => (
          <Steps.Step
            key={timestamp}
            icon={status ? <Star /> : <StarOutlined />}
          >
            <View>{timestamp}</View>
            <View>当前状态为: {String(status)}</View>
          </Steps.Step>
        ))}
      </Steps>
    </DemoContent>
  );
};
