// examples/taro-hooks-plugin-vue/src/pages/network/useRequest/ready/index.vue
<template>
  <block>
    <demo-content title="Ready - 自动模式">
      <view>Ready: {{ JSON.stringify(ready) }}</view>
      <nut-row justify="center">
        <nut-button
          :loading="request.loading"
          size="small"
          type="primary"
          shape="square"
          block
          @click="action.toggle()"
        >
          Toggle Ready
        </nut-button>
      </nut-row>
      <view>Username: {{ request.loading ? 'Loading...' : request.data }}</view>
    </demo-content>
  </block>
</template>

<script>
import { useRequest } from 'taro-hooks';
import { useToggle } from '@taro-hooks/ahooks';

import Mock from 'mockjs';

function getUsername() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock('@name()'));
    }, 1000);
  });
}
export default {
  setup() {
    const [ready, action] = useToggle(false);

    const request = useRequest(getUsername, {
      ready,
    });

    return { request, ready, action };
  },
};
</script>

// examples/taro-hooks-plugin/src/pages/useRequest/ready/index.tsx
import React from 'react';
import DemoContent from '@src/components/DemoContent';
import { Button, Field } from '@taroify/core';

import { useRequest } from 'taro-hooks';
import { useToggle } from '@taro-hooks/ahooks';
import Mock from 'mockjs';

function getUsername(): Promise<string> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock('@name'));
    }, 1000);
  });
}

export default () => {
  const [ready, { toggle }] = useToggle(false);

  const { data, loading } = useRequest(getUsername, {
    ready,
  });

  return (
    <DemoContent title="Ready - 自动模式">
      <Field align="start">Ready: {JSON.stringify(ready)}</Field>
      <Field align="center">
        <Button
          loading={loading}
          color="primary"
          size="small"
          block
          onClick={toggle}
        >
          Toggle Ready
        </Button>
      </Field>
      <Field align="start">Username: {loading ? 'Loading' : data}</Field>
    </DemoContent>
  );
};
