// examples/taro-hooks-plugin/src/pages/wechat/useMenuButtonBoundingClientRect/index.tsx
import React from 'react';
import { useMenuButtonBoundingClientRect } from 'taro-hooks';

import DemoContent from '@src/components/DemoContent';
import { Cell } from '@taroify/core';

export default () => {
  const rect = useMenuButtonBoundingClientRect();

  return (
    <DemoContent>
      {Object.keys(rect).length ? (
        <Cell.Group clickable>
          {Object.entries(rect).map(([key, value]) => (
            <Cell key={key} title={'位置 - ' + key}>
              {value}
            </Cell>
          ))}
        </Cell.Group>
      ) : (
        <Cell>暂无信息</Cell>
      )}
    </DemoContent>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/wechat/useMenuButtonBoundingClientRect/index.vue
<template>
  <demo-content>
    <nut-cell v-if="!emptyInfo">暂无信息</nut-cell>
    <nut-cell-group v-else>
      <nut-cell
        v-for="(value, key) in rect"
        :key="key"
        :title="'位置 - ' + key"
        :desc="$filters.stringify(value)"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useMenuButtonBoundingClientRect } from 'taro-hooks';

const rect = useMenuButtonBoundingClientRect();

const emptyInfo = Object.keys(rect)?.length;
</script>
