// examples/taro-hooks-plugin-vue/src/pages/wechat/useChooseAddress/index.vue
<template>
  <demo-content>
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="handleChoose()"
      >获取收货地址</nut-button
    >
    <nut-cell-group title="地址信息">
      <nut-cell
        v-for="(value, key) in address"
        :key="key"
        :title="key"
        :desc="value"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useState } from '@taro-hooks/core';
import { useChooseAddress, useModal } from 'taro-hooks';

const choose = useChooseAddress();
const show = useModal({ mask: true, title: '获取结果', showCancel: false });
const [address, setAddress] =
  useState<Taro.chooseAddress.SuccessCallbackResult>();

const handleChoose = async () => {
  let content = '获取成功';
  try {
    const result = await choose();
    setAddress(result);
  } catch (e) {
    content = e.errMsg || e.message;
  }
  show({ content });
};
</script>

// examples/taro-hooks-plugin/src/pages/wechat/useChooseAddress/index.tsx
import React from 'react';
import { useState } from '@taro-hooks/core';
import { useChooseAddress, useModal } from 'taro-hooks';
import DemoContent from '@src/components/DemoContent';
import { Button, Cell } from '@taroify/core';

export default () => {
  const choose = useChooseAddress({});
  const show = useModal({ mask: true, title: '获取结果', showCancel: false });
  const [address, setAddress] =
    useState<Taro.chooseAddress.SuccessCallbackResult>();

  const handleChoose = async () => {
    let content = '获取成功';
    try {
      const result = await choose();
      setAddress(result);
    } catch (e) {
      content = e.errMsg || e.message;
    }
    show({ content });
  };

  return (
    <DemoContent>
      <Button
        block
        color="primary"
        className="gap"
        onClick={handleChoose}
        shape="square"
      >
        获取收货地址
      </Button>
      {Object.keys(address).length ? (
        <Cell.Group clickable title="地址信息">
          {Object.entries(address).map(([key, value]) => (
            <Cell key={key} title={key}>
              {JSON.stringify(value)}
            </Cell>
          ))}
        </Cell.Group>
      ) : (
        <Cell>暂无信息</Cell>
      )}
    </DemoContent>
  );
};
