// examples/taro-hooks-plugin-vue/src/pages/basic/useRouter/index.vue
<template>
  <demo-content>
    <nut-cell
      title="来源页面"
      :sub-title="$filters.stringify(routerInfo?.from?.route)"
    ></nut-cell>
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="switchTab('pages/about/index')"
      >跳转TabBar</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="relaunch('/pages/network/useRequest/index')"
    >
      重新打开一个页面</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="redirect('/pages/network/useOnline/index')"
    >
      重定向页面</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="
        navigate('/pages/wechat/useLaunchOptions/index', { from: 'useRouter' })
      "
    >
      跳转页面</nut-button
    >
    <nut-button shape="square" type="primary" class="gap" block @click="back()">
      返回上一页</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="
        navigate(
          '/pages/index/index',
          { appId: 'wxce815e33b0e06cf5', extraData: { from: 'taro-hooks' } },
          true,
        )
      "
    >
      跳转小程序</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="
        navigate(
          '/pages/index/index',
          { appId: 'wxce815e33b0e06cf5', extraData: { from: 'taro-hooks' } },
          true,
          true,
        )
      "
    >
      半屏打开小程序</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="back({}, true)"
    >
      返回小程序</nut-button
    >
    <nut-button shape="square" type="primary" class="gap" block @click="exit()">
      退出小程序</nut-button
    >
    <nut-cell
      title="当前页面"
      :sub-title="$filters.stringify(routerInfo)"
    ></nut-cell>
  </demo-content>
</template>

<script setup lang="ts">
import { useRouter } from 'taro-hooks';

const [routerInfo, { navigate, switchTab, relaunch, redirect, back, exit }] =
  useRouter();
</script>

// packages/app/src/pages/useRouter/index.tsx
import React from 'react';
import { AtButton, AtNoticebar, AtList, AtListItem } from 'taro-ui';
import DocPage from '@components/DocPage';
import { View } from '@tarojs/components';

import { useRouter, useEnv } from 'taro-hooks';
import { ENV_TYPE } from '@tarojs/taro';

export default () => {
  const env = useEnv();
  const [
    routeInfo,
    { switchTab, relaunch, redirectTo, navigateTo, navigateBack },
  ] = useRouter();

  return (
    <>
      <AtNoticebar marquee>
        由于文档无路由输出。故移步小程序体验或下载包进行体验。
      </AtNoticebar>
      <DocPage title="useRouter 路由" panelTitle="useRouter">
        {routeInfo?.from?.route && (
          <AtList>
            <AtListItem title="来源页面" note={routeInfo?.from?.route} />
          </AtList>
        )}
        <AtButton
          disabled={env === ENV_TYPE.WEB}
          onClick={() => switchTab('/pages/about/index')}
        >
          跳转TabBar
        </AtButton>
        <AtButton
          className="gap"
          disabled={env === ENV_TYPE.WEB}
          onClick={() => relaunch('/pages/useRequest/index')}
        >
          重新打开一个页面
        </AtButton>
        <AtButton
          disabled={env === ENV_TYPE.WEB}
          onClick={() => redirectTo('/pages/useOnline/index')}
        >
          重定向页面
        </AtButton>
        <AtButton
          className="gap"
          disabled={env === ENV_TYPE.WEB}
          onClick={() =>
            navigateTo('/pages/useLaunchOptions/index', { from: 'useRoute' })
          }
        >
          跳转页面
        </AtButton>
        <AtButton
          disabled={env === ENV_TYPE.WEB}
          onClick={() => navigateBack()}
        >
          返回上一页
        </AtButton>
        <AtButton
          className="gap"
          disabled={env === ENV_TYPE.WEB}
          onClick={() =>
            navigateTo(true, {
              appId: 'wxce815e33b0e06cf5',
              extraData: { from: 'taro-hooks' },
            })
          }
        >
          跳转小程序
        </AtButton>
        <AtButton
          disabled={env === ENV_TYPE.WEB}
          onClick={() => navigateBack(true)}
        >
          返回小程序
        </AtButton>
        {env !== ENV_TYPE.WEB && (
          <View>
            routeInfo:
            <View style={{ wordBreak: 'break-all' }}>
              {JSON.stringify(routeInfo)}
            </View>
          </View>
        )}
      </DocPage>
    </>
  );
};
