// examples/taro-hooks-plugin-vue/src/pages/network/useOnline/index.vue
<template>
  <demo-content>
    <nut-cell-group>
      <nut-cell title="当前网络状态">
        <template v-slot:link>
          <nut-switch disable :model-value="online" />
        </template>
      </nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useOnline } from 'taro-hooks';

const online = useOnline();
</script>

// examples/taro-hooks-plugin/src/pages/network/useOnline/index.tsx
import React from 'react';
import { useOnline } from 'taro-hooks';

import DemoContent from '@src/components/DemoContent';
import { Cell, Switch } from '@taroify/core';

export default () => {
  const online = useOnline();

  return (
    <DemoContent>
      <Cell.Group clickable>
        <Cell title="当前网络状态">
          <Switch disabled checked={online} />
        </Cell>
      </Cell.Group>
    </DemoContent>
  );
};
