// examples/taro-hooks-plugin-vue/src/pages/network/useRequest/basic/params.vue
<template>
  <block>
    <demo-content title="Basic - 参数管理">
      <nut-input
        :disabled="request.loading"
        v-model="state"
        placeholder="Please enter userId"
      >
        <template #button>
          <nut-button
            :loading="request.loading"
            size="small"
            type="primary"
            shape="square"
            @click="request.run(state)"
            >{{ request.loading ? 'Loading' : 'GetUserName' }}</nut-button
          >
        </template>
      </nut-input>
      <view>UserId: {{ request.params[0] }}</view>
      <view>UserName: {{ request.data }}</view>
    </demo-content>
  </block>
</template>

<script>
import { useState } from '@taro-hooks/core';
import { useRequest } from 'taro-hooks';
import Mock from 'mockjs';

function getUsername(id) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(Mock.mock('@name()'));
    }, 1000);
  });
}

export default {
  setup() {
    const [state] = useState('');
    const request = useRequest(getUsername, {
      defaultParams: ['1'],
    });

    return {
      request,
      state,
    };
  },
};
</script>

// examples/taro-hooks-plugin/src/pages/network/useRequest/basic/params.tsx
import React from 'react';
import { View } from '@tarojs/components';
import DemoContent from '@src/components/DemoContent';
import { Button, Input, Field } from '@taroify/core';

import { useState } from '@taro-hooks/core';
import { useRequest } from 'taro-hooks';
import Mock from 'mockjs';

function getUsername(): Promise<string> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(Mock.mock('@name()'));
    }, 1000);
  });
}

export default () => {
  const [state, setState] = useState('');

  // get username
  const {
    data: username,
    run,
    params,
    loading,
  } = useRequest(getUsername, {
    defaultParams: ['1'],
  });

  const onChange = () => {
    run(state);
  };

  return (
    <DemoContent title="Basic - 参数管理">
      <Field align="center">
        <Input
          onChange={(e) => setState(e.detail.value)}
          value={state}
          placeholder="Please enter userId"
        />
        <Button
          disabled={loading}
          loading={loading}
          color="primary"
          size="small"
          onClick={onChange}
        >
          {loading ? 'Loading' : 'Edit'}
        </Button>
      </Field>
      <View>UserId: {params?.[0]}</View>
      <View>Username: {username}</View>
    </DemoContent>
  );
};
