// examples/taro-hooks-plugin-vue/src/pages/network/useNetworkType/index.vue
<template>
  <demo-content>
    <nut-radiogroup v-model="networkType">
      <nut-radio
        v-for="(value, key) in NETWORKTYPE"
        :key="key"
        :disabled="value !== networkType"
        :label="value"
        shape="button"
        >网络类型: {{ value }}</nut-radio
      >
    </nut-radiogroup>
  </demo-content>
</template>

<script setup lang="ts">
import { showToast } from '@tarojs/taro';
import { useEffect } from '@taro-hooks/core';
import { useNetworkType } from 'taro-hooks';
import { escapeState } from '@taro-hooks/shared';
// @ts-ignore
import { NETWORKTYPE } from '@root/public/constant';

const networkType = useNetworkType();

useEffect(() => {
  showToast({
    title: `当前网络类型为: ${escapeState(networkType)}`,
    icon: 'none',
    mask: true,
  });
}, [networkType]);
</script>

// examples/taro-hooks-plugin/src/pages/network/useNetworkType/index.tsx
import React from 'react';
import DemoContent from '@src/components/DemoContent';
import { Radio, Cell } from '@taroify/core';
import { showToast } from '@tarojs/taro';
import { useEffect } from '@taro-hooks/core';
import { escapeState } from '@taro-hooks/shared';
import { useNetworkType } from 'taro-hooks';
// @ts-ignore
import { NETWORKTYPE } from '@root/public/constant';

export default () => {
  const networkType = useNetworkType();

  useEffect(() => {
    showToast({
      title: `当前网络类型为: ${escapeState(networkType)}`,
      icon: 'none',
      mask: true,
    });
  }, [networkType]);

  return (
    <DemoContent>
      <Radio.Group value={escapeState(networkType)}>
        <Cell.Group clickable>
          {Object.entries(NETWORKTYPE).map(([key, value]) => (
            <Cell key={key} title={'网络类型: ' + value}>
              <Radio
                disabled={value !== escapeState(networkType)}
                name={value}
              />
            </Cell>
          ))}
        </Cell.Group>
      </Radio.Group>
    </DemoContent>
  );
};
