// examples/taro-hooks-plugin/src/pages/device/useBattery/index.tsx
import React from 'react';
import { useBattery } from 'taro-hooks';

import DemoContent from '@src/components/DemoContent';
import { Cell, Progress, Switch } from '@taroify/core';

export default () => {
  const batteryInfo = useBattery();

  return (
    <DemoContent>
      <Cell.Group clickable>
        <Cell title="充电与否">
          <Switch disabled checked={batteryInfo.isCharging} />
        </Cell>
        <Cell title="电量" brief={<Progress percent={batteryInfo.level} />}>
          {batteryInfo.level}
        </Cell>
      </Cell.Group>
    </DemoContent>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/device/useBattery/index.vue
<template>
  <demo-content>
    <nut-cell-group>
      <nut-cell title="充电与否">
        <template v-slot:link>
          <nut-switch disable :model-value="batteryInfo.isCharging" />
        </template>
      </nut-cell>
      <nut-cell title="电量">
        <nut-progress :percentage="batteryInfo.level" />
      </nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useBattery } from 'taro-hooks';

const batteryInfo = useBattery();
</script>
