// packages/app-vue/src/pages/NavBar/index.tsx
import { defineComponent } from 'vue';
import { showToast } from '@tarojs/taro';
import { NavBar, Space } from 'ant-mobile-taro';
import { View } from '@tarojs/components';
import DemoBlock from '@components/DemoBlock/index.vue';
import { Search, Dash, Close } from 'ant-mobile-icon-taro/es/index.vue';

import './index.less';

export default defineComponent({
  name: 'NavBarDemo',
  setup() {
    const right = (
      <View style={{ fontSize: 18 }}>
        <Space>
          <Search />
          <Dash />
        </Space>
      </View>
    );

    const back = () =>
      showToast({
        title: '点击了返回区域',
        duration: 1000,
      });

    return () => (
      <>
        <DemoBlock title="基础使用" padding="0">
          <NavBar onBack={back}>标题</NavBar>
        </DemoBlock>

        <DemoBlock title="自定义返回按钮的文字" padding="0">
          <NavBar back="返回" onBack={back}>
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="返回按钮不显示图标" padding="0">
          <NavBar back="返回" onBack={back} backArrow={false}>
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义返回按钮图标" padding="0">
          <NavBar onBack={back}>
            {{
              default: () => '标题',
              back: () => '返回',
              backArrow: (props) => <Close {...props} />,
            }}
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义左侧区域" padding="0">
          <NavBar back="返回" onBack={back} left="关闭">
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义右侧区域" padding="0">
          <NavBar right={right} onBack={back}>
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义标题内容" padding="0">
          <NavBar onBack={back}>
            <View>
              <View>标题</View>
              <View className="my-nav-bar-subtitle">副标题</View>
            </View>
          </NavBar>
        </DemoBlock>

        <DemoBlock title="自定义高度和下边框" padding="0">
          <NavBar
            style={{
              '--height': '36px',
              '--border-bottom': '1px #eee solid',
            }}
            onBack={back}
          >
            标题
          </NavBar>
        </DemoBlock>

        <DemoBlock title="标题超长自动省略" padding="0">
          <NavBar onBack={back}>这是一条很长很长很长很长很长很长的标题</NavBar>
        </DemoBlock>
      </>
    );
  },
});

// ant-mobile-taro/src/components/nav-bar/nav-bar.vue.tsx
/* eslint-disable react/react-in-jsx-scope */
import classNames from 'classnames'
import { View, Text, ITouchEvent } from '@tarojs/components'
import { Left } from 'ant-mobile-icon-taro/es/index.vue'
import { withNativeProps, ISetupContext } from '../../utils/native-props.vue'

const classPrefix = `adm-nav-bar`

export const NavBarProps = {
  back: {
    type: String,
    default: '',
  },
  backArrow: {
    type: [Boolean, Function, Object],
    default: true,
  },
  left: [String, Function, Object],
  right: [String, Function, Object],
}

export const NavBar = withNativeProps({
  name: 'NavBar',
  props: NavBarProps,
  emits: ['back'],
  setup(
    props,
    { attrs, slots, emit }: ISetupContext<'--height' | '--border-bottom'>
  ) {
    const handleBack = (event: ITouchEvent) => {
      emit('back', event)
    }
    return () => (
      <View className={classNames(classPrefix, attrs.className, attrs.class)}>
        <View className={`${classPrefix}-left`} role='button'>
          {(slots.back || props.back) !== null && (
            <View className={`${classPrefix}-back`} onClick={handleBack}>
              {(slots.backArrow || props.backArrow) && (
                <Text className={`${classPrefix}-back-arrow`}>
                  {(slots.backArrow || props.backArrow) === true ? (
                    <Left />
                  ) : (
                    slots.backArrow?.() || props.backArrow
                  )}
                </Text>
              )}
              <Text aria-hidden='true'>{slots.back?.() || props.back}</Text>
            </View>
          )}
          {slots.left?.() || props.left}
        </View>
        <View className={`${classPrefix}-title`}>{slots.default?.()}</View>
        <View className={`${classPrefix}-right`}>
          {slots.right?.() || props.right}
        </View>
      </View>
    )
  },
})
