// packages/app-vue/src/pages/PageIndicator/index.tsx
import { defineComponent } from 'vue';
import { PageIndicator } from 'ant-mobile-taro';
import DemoBlock from '@components/DemoBlock/index.vue';

export default defineComponent({
  name: 'PageIndicatorDemo',
  setup() {
    return () => (
      <>
        <DemoBlock title="基础用法">
          <PageIndicator total={4} current={0} />
        </DemoBlock>
        <DemoBlock title="白色" background="rgb(212 212 212)">
          <PageIndicator total={4} current={0} color="white" />
        </DemoBlock>
        <DemoBlock title="竖直方向">
          <PageIndicator total={4} current={0} direction="vertical" />
        </DemoBlock>
        <DemoBlock title="自定义颜色和大小">
          <PageIndicator
            total={4}
            current={0}
            style={{
              '--dot-color': 'rgba(0, 0, 0, 0.4)',
              '--active-dot-color': '#ffc0cb',
              '--dot-size': '10px',
              '--active-dot-size': '30px',
              '--dot-border-radius': '50%',
              '--active-dot-border-radius': '15px',
              '--dot-spacing': '8px',
            }}
          />
        </DemoBlock>
      </>
    );
  },
});

// packages/app/src/ui/PageIndicator/index.tsx
import React from 'react';
import { PageIndicator } from 'ant-mobile-taro';
import DemoBlock from '@components/DemoBlock';

export default () => {
  return (
    <>
      <DemoBlock title="基础用法">
        <PageIndicator total={4} current={0} />
      </DemoBlock>
      <DemoBlock title="白色" background="rgb(212 212 212)">
        <PageIndicator total={4} current={0} color="white" />
      </DemoBlock>
      <DemoBlock title="竖直方向">
        <PageIndicator total={4} current={0} direction="vertical" />
      </DemoBlock>
      <DemoBlock title="自定义颜色和大小">
        <PageIndicator
          total={4}
          current={0}
          style={{
            '--dot-color': 'rgba(0, 0, 0, 0.4)',
            '--active-dot-color': '#ffc0cb',
            '--dot-size': '10px',
            '--active-dot-size': '30px',
            '--dot-border-radius': '50%',
            '--active-dot-border-radius': '15px',
            '--dot-spacing': '8px',
          }}
        />
      </DemoBlock>
    </>
  );
};
