// ant-mobile-taro/src/utils/use-resize-effect.vue.tsx
import { onMounted, onUpdated, Component, ref, onUnmounted, Ref } from 'vue'
import { onWindowResize, offWindowResize } from '@tarojs/taro'

export function useResizeEffect<T extends Component<any>>(
  effect: (target: T) => void,
  targetRef: Ref<T>
) {
  const fn = ref(effect)
  const observer = ref()

  const observerResize = () => {
    const target = targetRef.value?.$el
    if (!target) return
    if (window?.ResizeObserver) {
      observer.value = new ResizeObserver(() => {
        fn.value(target)
      })
      observer.value.observe(target as unknown as Element)
    } else {
      onWindowResize(() => {
        fn.value(target)
      })
    }
  }

  onMounted(observerResize)

  onUpdated(observerResize)

  onUnmounted(() => {
    if (observer.value) {
      observer.value.disconnect()
    } else {
      offWindowResize(() => fn.value(targetRef.value))
    }
  })
}

// ant-mobile-taro/src/utils/use-resize-effect.tsx
import { RefObject, useLayoutEffect, ComponentType } from 'react'
import { onWindowResize, offWindowResize } from '@tarojs/taro'
import { useMemoizedFn } from 'ahooks'

export function useResizeEffect<T extends ComponentType<any>>(
  effect: (target: T) => void,
  targetRef: RefObject<T>
) {
  const fn = useMemoizedFn(effect)
  useLayoutEffect(() => {
    const target = targetRef.current
    if (!target) return
    if (window?.ResizeObserver) {
      const observer = new ResizeObserver(() => {
        fn(target)
      })
      observer.observe(target as unknown as Element)
      return () => {
        observer.disconnect()
      }
    } else {
      onWindowResize(() => {
        fn(target)
      })
    }

    return () => {
      offWindowResize(() => fn(target))
    }
  }, [targetRef])
}
