// ant-mobile-taro/src/components/divider/divider.vue.tsx
/* eslint-disable react/react-in-jsx-scope */
import { PropType } from 'vue'
import { View } from '@tarojs/components'
import classNames from 'classnames'
import { withNativeProps } from '../../utils/native-props.vue'

const classPrefix = `adm-divider`

export type DividerContentPosition = 'left' | 'right' | 'center'
export const DividerProps = {
  contentPosition: {
    type: String as PropType<DividerContentPosition>,
    default: 'center',
  },
}

export const Divider = withNativeProps({
  name: 'Divider',
  props: DividerProps,
  setup(props, { slots }) {
    return () => (
      <View
        className={classNames(
          classPrefix,
          `${classPrefix}-${props.contentPosition}`
        )}
      >
        {slots?.default && (
          <View className={`${classPrefix}-content`}>{slots.default()}</View>
        )}
      </View>
    )
  },
})

// ant-mobile-taro/src/components/divider/divider.tsx
import React, { FC } from 'react'
import { View } from '@tarojs/components'
import classNames from 'classnames'
import { NativeProps, withNativeProps } from '../../utils/native-props'
import { mergeProps } from '../../utils/with-default-props'

const classPrefix = `adm-divider`

export type DividerProps = {
  contentPosition?: 'left' | 'right' | 'center'
} & NativeProps

const defaultProps = {
  contentPosition: 'center',
}

export const Divider: FC<DividerProps> = p => {
  const props = mergeProps(defaultProps, p)
  return withNativeProps(
    props,
    <View
      className={classNames(
        classPrefix,
        `${classPrefix}-${props.contentPosition}`
      )}
    >
      {props.children && (
        <View className={`${classPrefix}-content`}>{props.children}</View>
      )}
    </View>
  )
}
