// packages/app/src/pages/useTopBarText/index.tsx
import React, { useCallback } from 'react';
import { AtNoticebar, AtButton } from 'taro-ui';
import DocPage from '@components/DocPage';

import Mock from 'mockjs';
import { useTopBarText, useModal } from 'taro-hooks';
import { General } from '@tarojs/taro';

export default () => {
  const [show] = useModal({ mask: true, title: '设置结果', showCancel: false });
  const [set] = useTopBarText('taro-hooks');

  const handleSetTopBarText = useCallback(async () => {
    try {
      const result = await set(Mock.mock('@name()'));
      show({ content: result.errMsg });
    } catch (e) {
      show({ content: (e as General.CallbackResult).errMsg });
    }
  }, [show, set]);

  return (
    <>
      <AtNoticebar marquee>
        该hook仅小程序使用. 请将小程序置顶查看效果
      </AtNoticebar>
      <DocPage title="useTopBarText 置顶文字" panelTitle="useTopBarText">
        <AtButton onClick={handleSetTopBarText}>设置置顶栏文字内容</AtButton>
      </DocPage>
    </>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/wechat/useTopBarText/index.vue
<template>
  <demo-content>
    <nut-button shape="square" type="primary" block @click="handleClick()"
      >设置置顶栏文字内容</nut-button
    >
  </demo-content>
</template>

<script setup lang="ts">
import { useTopBarText, useModal } from 'taro-hooks';
import Mock from 'mockjs';

const set = useTopBarText('taro-hooks');
const show = useModal({ mask: true, title: '设置结果', showCancel: false });

const handleClick = async () => {
  let content = '';
  try {
    const { errMsg } = await set(Mock.Random.name());
    content = errMsg;
  } catch (e) {
    content = e.errMsg || e.message;
  }
  show({ content });
};
</script>
