// ant-mobile-taro/src/components/loading/loading.tsx
import React, { memo } from 'react'
import { View } from '@tarojs/components'
import { mergeProps } from '../../utils/with-default-props'
import { NativeProps, withNativeProps } from '../../utils/native-props'
import hex2rgb from '../../utils/hex2rgb'
import loadingContent from './icon'

const classPrefix = `adm-loading`

const colorRecord: Record<string, string> = {
  default: '#999999',
  primary: '#1677ff',
  white: '#ffffff',
}

export type LoadingProps = {
  color?: 'default' | 'primary' | 'white' | (string & {})
} & NativeProps

const defaultProps = {
  color: 'default',
}

export const Loading = memo<LoadingProps>(p => {
  const props = mergeProps(defaultProps, p)
  const loadingColor = hex2rgb(colorRecord[props.color] ?? props.color)
  return withNativeProps(
    props,
    <View
      style={{
        color: loadingColor,
        background: `url("${loadingContent(
          loadingColor
        )}") center center / contain no-repeat`,
      }}
      className={classPrefix}
    ></View>
  )
})

// ant-mobile-taro/src/components/loading/loading.vue.tsx
/* eslint-disable react/react-in-jsx-scope */
import { PropType } from 'vue'
import classNames from 'classnames'
import { View } from '@tarojs/components'
import { withNativeProps } from '../../utils/native-props.vue'
import hex2rgb from '../../utils/hex2rgb'
import loadingContent from './icon'

const classPrefix = `adm-loading`

const colorRecord: Record<string, string> = {
  default: '#999999',
  primary: '#1677ff',
  white: '#ffffff',
}

export type LoadingColor = 'default' | 'primary' | 'white' | string

const LoadingProps = {
  color: {
    type: String as PropType<LoadingColor>,
    default: 'default',
  },
}

export default withNativeProps({
  name: 'Loading',
  props: LoadingProps,
  setup(props, { attrs }) {
    const loadingColor = hex2rgb(colorRecord[props.color] ?? props.color)
    return () => (
      <View
        {...attrs}
        style={{
          color: loadingColor,
          background: `url("${loadingContent(
            loadingColor
          )}") center center / contain no-repeat`,
        }}
        className={classNames(classPrefix, attrs.class, attrs.className)}
      ></View>
    )
  },
})
