// packages/app/src/ui/Steps/index.tsx
import React from 'react';
import { Steps } from 'ant-mobile-taro';
import DemoBlock from '@components/DemoBlock';
import {
  CheckCircle,
  FieldTime,
  Transaction,
} from 'ant-mobile-icon-taro/es/index.react';

const { Step } = Steps;

export default () => {
  return (
    <>
      <DemoBlock title="横向">
        <Steps current={1}>
          <Step title="标题1" description="描述" />
          <Step title="标题2" description="描述" />
          <Step title="标题3" description="描述" />
        </Steps>
      </DemoBlock>

      <DemoBlock title="横向（失败状态）">
        <Steps current={2}>
          <Step title="第一步" />
          <Step title="第二步" />
          <Step title="第三步" status="error" />
        </Steps>
      </DemoBlock>

      <DemoBlock title="纵向">
        <Steps direction="vertical">
          <Step title="填写机构信息" status="process" />
          <Step title="签约机构" status="wait" />
          <Step title="关联服务区" status="wait" />
        </Steps>
      </DemoBlock>

      <DemoBlock title="纵向（失败状态）">
        <Steps direction="vertical">
          <Step
            title="填写机构信息"
            status="finish"
            description="完成时间：2020-12-01 12:30"
          />
          <Step
            title="签约机构"
            status="finish"
            description="完成时间：2020-12-01 12:30"
          />
          <Step
            title="关联服务区"
            status="finish"
            description="完成时间：2020-12-01 12:30"
          />
          <Step title="审批失败" status="error" />
        </Steps>
      </DemoBlock>

      <DemoBlock title="自定义图标">
        <Steps direction="vertical" current={1}>
          <Step
            title="第一步"
            description="完成人1111"
            icon={<CheckCircle />}
          />
          <Step title="第二步" description="完成人1111" icon={<FieldTime />} />
          <Step
            title="第三步"
            description="完成人1111"
            icon={<Transaction />}
          />
        </Steps>
      </DemoBlock>
    </>
  );
};

// packages/app-vue/src/pages/Steps/index.tsx
import { defineComponent } from 'vue';
import { Steps } from 'ant-mobile-taro';
import DemoBlock from '@components/DemoBlock/index.vue';
import {
  CheckCircle,
  FieldTime,
  Transaction,
} from 'ant-mobile-icon-taro/es/index.vue';

const { Step } = Steps;

export default defineComponent({
  name: 'StepsDemo',
  setup() {
    return () => (
      <>
        <DemoBlock title="横向">
          <Steps current={1}>
            <Step title="标题1" description="描述" />
            <Step title="标题2" description="描述" />
            <Step title="标题3" description="描述" />
          </Steps>
        </DemoBlock>

        <DemoBlock title="横向（失败状态）">
          <Steps current={2}>
            <Step title="第一步" />
            <Step title="第二步" />
            <Step title="第三步" status="error" />
          </Steps>
        </DemoBlock>

        <DemoBlock title="纵向">
          <Steps direction="vertical">
            <Step title="填写机构信息" status="process" />
            <Step title="签约机构" status="wait" />
            <Step title="关联服务区" status="wait" />
          </Steps>
        </DemoBlock>

        <DemoBlock title="纵向（失败状态）">
          <Steps direction="vertical">
            <Step
              title="填写机构信息"
              status="finish"
              description="完成时间：2020-12-01 12:30"
            />
            <Step
              title="签约机构"
              status="finish"
              description="完成时间：2020-12-01 12:30"
            />
            <Step
              title="关联服务区"
              status="finish"
              description="完成时间：2020-12-01 12:30"
            />
            <Step title="审批失败" status="error" />
          </Steps>
        </DemoBlock>

        <DemoBlock title="自定义图标">
          <Steps direction="vertical" current={1}>
            <Step
              title="第一步"
              description="完成人1111"
              icon={<CheckCircle />}
            />
            <Step>
              {{
                title: () => '第二步',
                description: () => '完成人1111',
                icon: (props) => <FieldTime {...props} />,
              }}
            </Step>
            <Step
              title="第三步"
              description="完成人1111"
              icon={<Transaction />}
            />
          </Steps>
        </DemoBlock>
      </>
    );
  },
});
