// examples/taro-hooks-plugin-vue/src/pages/device/useBrightness/index.vue
<template>
  <demo-content>
    <nut-cell-group>
      <nut-cell title="当前亮度">
        <nut-progress :percentage="(brightness || 0) * 100" />
      </nut-cell>
      <nut-cell title="设置亮度">
        <nut-range
          :min="0"
          :max="1"
          :step="0.1"
          v-model="rangeBrightness"
          @change="setBrightness($event)"
        ></nut-range>
      </nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useBrightness } from 'taro-hooks';
import { useTaroState } from '@tarojs/taro';

const [rangeBrightness] = useTaroState<string>();

const [brightness, setBrightness] = useBrightness();
</script>

// packages/app/src/pages/useBrightness/index.tsx
import React from 'react';
import { AtProgress, AtSlider } from 'taro-ui';
import DocPage from '@components/DocPage';
import { View } from '@tarojs/components';

import { useBrightness } from 'taro-hooks';

export default () => {
  const [brightness, setBrightness] = useBrightness(true);
  return (
    <DocPage title="useBrightness 屏幕亮度" panelTitle="useBrightness">
      <View className="at-article__h3">当前亮度</View>
      <AtProgress percent={brightness * 100} />
      <View className="at-article__h3">设置亮度</View>
      <AtSlider
        min={0}
        max={1}
        step={0.1}
        value={brightness}
        onChange={(value) => setBrightness(value.toFixed(1))}
      ></AtSlider>
    </DocPage>
  );
};
