// packages/app/src/pages/useScanCode/index.tsx
import React, { useCallback } from 'react';
import { AtButton, AtNoticebar } from 'taro-ui';
import DocPage from '@components/DocPage';

import { scanCode } from '@tarojs/taro';
import { useScanCode, useModal } from 'taro-hooks';

export default () => {
  const [show] = useModal({ mask: true, title: '扫码结果', showCancel: false });
  const [scan, cameraScan] = useScanCode();

  const handleScan = useCallback(
    (scanType?: keyof scanCode.ScanType) => {
      scan({ scanType }).then((res: scanCode.SuccessCallbackResult) => {
        show({ content: JSON.stringify(res) });
      });
    },
    [scan, show],
  );

  const handleCameraScan = useCallback(() => {
    cameraScan().then((res: scanCode.SuccessCallbackResult) => {
      show({ content: JSON.stringify(res) });
    });
  }, [cameraScan, show]);

  return (
    <>
      <AtNoticebar marquee>h5端扫码仅在微信公众号内可用</AtNoticebar>
      <DocPage title="useScanCode 扫码" panelTitle="useScanCode">
        <AtButton onClick={() => handleScan()}>普通扫码</AtButton>
        <AtButton className="gap" onClick={handleCameraScan}>
          相机扫码
        </AtButton>
        <AtButton onClick={() => handleScan('qrCode')}>扫二维码</AtButton>
      </DocPage>
    </>
  );
};

// examples/taro-hooks-plugin-vue/src/pages/device/useScanCode/index.vue
<template>
  <demo-content>
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleScan()"
      >普通扫码</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleCameraScan()"
      >相机扫码</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleScan('qrCode')"
      >扫二维码</nut-button
    >
  </demo-content>
</template>

<script setup lang="ts">
import { useScanCode, useModal } from 'taro-hooks';

const { scan, cameraScan } = useScanCode();
const show = useModal({ mask: true, title: '扫码结果', showCancel: false });

const handleScan = async (scanType?) => {
  let content = '';
  try {
    const res = await scan({ scanType });
    content = JSON.stringify(res);
  } catch (e) {
    content = e.errMsg || e.message;
  }
  show({ content });
};

const handleCameraScan = async () => {
  let content = '';
  try {
    const res = await cameraScan();
    content = JSON.stringify(res);
  } catch (e) {
    content = e.errMsg || e.message;
  }
  show({ content });
};
</script>
