// examples/taro-hooks-plugin-vue/src/pages/basic/usePage/index.vue
<template>
  <demo-content>
    <nut-cell title="路由栈长度" :sub-title="stackLength"></nut-cell>
    <nut-cell
      title="当前页面信息"
      :sub-title="$filters.stringify(pageInstance)"
    ></nut-cell>
  </demo-content>
</template>

<script setup lang="ts">
import { usePage } from 'taro-hooks';

const [stackLength, { pageInstance = {} }] = usePage();
</script>

// packages/app/src/pages/usePage/index.tsx
import React from 'react';
import { AtList, AtListItem, AtNoticebar } from 'taro-ui';
import DocPage from '@components/DocPage';

import { usePage } from 'taro-hooks';

export default () => {
  const [stackLength, { pageInstance, pageStack, useScope }] = usePage();

  const scope = useScope();

  return (
    <>
      <AtNoticebar marquee>
        文档中的用例非完整应用, 可查看h5 或 小程序 demo 查看效果.
        具体部分信息需查看控制台
      </AtNoticebar>
      <DocPage title="usePage 页面(栈)" panelTitle="usePage">
        <AtList>
          <AtListItem title="路由栈长度" extraText={stackLength} />
          <AtListItem title="当前页面信息" note={JSON.stringify(scope || {})} />
        </AtList>
      </DocPage>
    </>
  );
};
