// examples/taro-hooks-plugin-vue/src/pages/wechat/useChooseAddress/index.vue
<template>
  <demo-content>
    <nut-button
      class="gap"
      shape="square"
      type="primary"
      block
      @click="handleChoose()"
      >获取收货地址</nut-button
    >
    <nut-cell-group title="地址信息">
      <nut-cell
        v-for="(value, key) in address"
        :key="key"
        :title="key"
        :desc="value"
      ></nut-cell>
    </nut-cell-group>
  </demo-content>
</template>

<script setup lang="ts">
import { useState } from '@taro-hooks/core';
import { useChooseAddress, useModal } from 'taro-hooks';

const choose = useChooseAddress();
const show = useModal({ mask: true, title: '获取结果', showCancel: false });
const [address, setAddress] =
  useState<Taro.chooseAddress.SuccessCallbackResult>();

const handleChoose = async () => {
  let content = '获取成功';
  try {
    const result = await choose();
    setAddress(result);
  } catch (e) {
    content = e.errMsg || e.message;
  }
  show({ content });
};
</script>

// packages/app/src/pages/useChooseAddress/index.tsx
import React, { useCallback, useState } from 'react';
import { AtButton, AtRadio } from 'taro-ui';

import DocPage from '@components/DocPage';

import { useModal, useChooseAddress } from 'taro-hooks';

export default () => {
  const [addressInfo, setAddressInfo] = useState({});
  const [show] = useModal({ mask: true, title: '获取结果', showCancel: false });
  const [chooseAddress] = useChooseAddress();

  const handleRequestSubscribeMessage = useCallback(async () => {
    let content = '获取成功!';
    try {
      const address = await chooseAddress();
      if (!address) {
        content = '获取失败';
      } else {
        setAddressInfo(address);
      }
    } catch (e) {
      content = '获取失败';
    }
    show({ content });
  }, [chooseAddress, show]);

  return (
    <DocPage title="useChooseAddress 收货地址" panelTitle="useChooseAddress">
      <AtButton onClick={handleRequestSubscribeMessage}>获取收货地址</AtButton>
      <AtRadio
        value={null}
        options={Object.entries(addressInfo).map(([key, value]) => ({
          label: key,
          value,
          desc: value as string,
        }))}
      />
    </DocPage>
  );
};
