// examples/taro-hooks-plugin-vue/src/pages/feedback/useToast/index.vue
<template>
  <demo-content>
    <nut-button shape="square" type="primary" class="gap" block @click="show()"
      >展示带初始配置的Toast</nut-button
    >
    <nut-button
      shape="square"
      type="primary"
      class="gap"
      block
      @click="handleChangeOption()"
      >展示新配置的Toast</nut-button
    >
    <nut-button shape="square" type="primary" block @click="hide()"
      >隐藏新配置的Toast</nut-button
    >
  </demo-content>
</template>

<script setup lang="ts">
import { useToast } from 'taro-hooks';

const { show, hide } = useToast({ title: 'initial title' });

const handleChangeOption = () => {
  show({
    icon: 'error',
    title: '点击隐藏按钮进行隐藏',
    duration: 3000000,
  });
};
</script>

// packages/app/src/pages/useToast/index.tsx
import React, { useCallback } from 'react';
import { AtButton } from 'taro-ui';
import DocPage from '@components/DocPage';

import { useToast } from 'taro-hooks';
import image from '../../assets/icon/about-select.png';

export default () => {
  const [show, hide] = useToast({
    mask: true,
    duration: 1000,
    title: 'initial title',
    icon: 'success',
  });

  const showCustomToast = useCallback(() => {
    show({
      title: '点击隐藏按钮进行隐藏',
      image,
      duration: 3000000,
      mask: false,
    });
  }, [show]);

  return (
    <>
      <DocPage title="useToast 消息提示框" panelTitle="useToast">
        <AtButton onClick={show}>展示带初始配置Toast</AtButton>
        <AtButton className="gap" onClick={showCustomToast}>
          展示新配置Toast
        </AtButton>
        <AtButton onClick={hide}>隐藏新配置Toast</AtButton>
      </DocPage>
    </>
  );
};
